# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\appli\foundation\gui\foundation\_src\ts_entitiesDial.ui'
#
# Created: Sat Feb 06 14:26:41 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dial_entities(object):
    def setupUi(self, Dial_entities):
        Dial_entities.setObjectName(_fromUtf8("Dial_entities"))
        Dial_entities.resize(330, 207)
        self.gridLayout = QtGui.QGridLayout(Dial_entities)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.line = QtGui.QFrame(Dial_entities)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 7, 0, 1, 1)
        self.hl_buttons = QtGui.QHBoxLayout()
        self.hl_buttons.setSpacing(0)
        self.hl_buttons.setObjectName(_fromUtf8("hl_buttons"))
        spacerItem1 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_buttons.addItem(spacerItem1)
        self.pb_save = QtGui.QPushButton(Dial_entities)
        self.pb_save.setMaximumSize(QtCore.QSize(60, 20))
        self.pb_save.setObjectName(_fromUtf8("pb_save"))
        self.hl_buttons.addWidget(self.pb_save)
        self.pb_cancel = QtGui.QPushButton(Dial_entities)
        self.pb_cancel.setMaximumSize(QtCore.QSize(60, 20))
        self.pb_cancel.setObjectName(_fromUtf8("pb_cancel"))
        self.hl_buttons.addWidget(self.pb_cancel)
        self.gridLayout.addLayout(self.hl_buttons, 9, 0, 1, 1)
        self.hl_name = QtGui.QHBoxLayout()
        self.hl_name.setObjectName(_fromUtf8("hl_name"))
        self.l_name = QtGui.QLabel(Dial_entities)
        self.l_name.setMinimumSize(QtCore.QSize(80, 0))
        self.l_name.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_name.setObjectName(_fromUtf8("l_name"))
        self.hl_name.addWidget(self.l_name)
        self.le_name = QtGui.QLineEdit(Dial_entities)
        self.le_name.setMinimumSize(QtCore.QSize(100, 0))
        self.le_name.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_name.setFrame(False)
        self.le_name.setObjectName(_fromUtf8("le_name"))
        self.hl_name.addWidget(self.le_name)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_name.addItem(spacerItem2)
        self.gridLayout.addLayout(self.hl_name, 6, 0, 1, 1)
        self.line_3 = QtGui.QFrame(Dial_entities)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 0, 1, 1)
        self.hl_type = QtGui.QHBoxLayout()
        self.hl_type.setObjectName(_fromUtf8("hl_type"))
        self.l_type = QtGui.QLabel(Dial_entities)
        self.l_type.setMinimumSize(QtCore.QSize(80, 0))
        self.l_type.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_type.setObjectName(_fromUtf8("l_type"))
        self.hl_type.addWidget(self.l_type)
        self.le_type = QtGui.QLineEdit(Dial_entities)
        self.le_type.setMinimumSize(QtCore.QSize(100, 0))
        self.le_type.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_type.setFrame(False)
        self.le_type.setObjectName(_fromUtf8("le_type"))
        self.hl_type.addWidget(self.le_type)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_type.addItem(spacerItem3)
        self.gridLayout.addLayout(self.hl_type, 4, 0, 1, 1)
        self.l_message = QtGui.QLabel(Dial_entities)
        self.l_message.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l_message.setFont(font)
        self.l_message.setAlignment(QtCore.Qt.AlignCenter)
        self.l_message.setObjectName(_fromUtf8("l_message"))
        self.gridLayout.addWidget(self.l_message, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(Dial_entities)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 1)
        self.hl_context = QtGui.QHBoxLayout()
        self.hl_context.setObjectName(_fromUtf8("hl_context"))
        self.l_context = QtGui.QLabel(Dial_entities)
        self.l_context.setMinimumSize(QtCore.QSize(80, 0))
        self.l_context.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_context.setObjectName(_fromUtf8("l_context"))
        self.hl_context.addWidget(self.l_context)
        self.le_context = QtGui.QLineEdit(Dial_entities)
        self.le_context.setMinimumSize(QtCore.QSize(100, 0))
        self.le_context.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_context.setFrame(False)
        self.le_context.setObjectName(_fromUtf8("le_context"))
        self.hl_context.addWidget(self.le_context)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_context.addItem(spacerItem4)
        self.gridLayout.addLayout(self.hl_context, 3, 0, 1, 1)
        self.hl_code = QtGui.QHBoxLayout()
        self.hl_code.setObjectName(_fromUtf8("hl_code"))
        self.l_code = QtGui.QLabel(Dial_entities)
        self.l_code.setMinimumSize(QtCore.QSize(80, 0))
        self.l_code.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_code.setObjectName(_fromUtf8("l_code"))
        self.hl_code.addWidget(self.l_code)
        self.le_code = QtGui.QLineEdit(Dial_entities)
        self.le_code.setMinimumSize(QtCore.QSize(100, 0))
        self.le_code.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_code.setFrame(False)
        self.le_code.setObjectName(_fromUtf8("le_code"))
        self.hl_code.addWidget(self.le_code)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_code.addItem(spacerItem5)
        self.gridLayout.addLayout(self.hl_code, 5, 0, 1, 1)

        self.retranslateUi(Dial_entities)
        QtCore.QMetaObject.connectSlotsByName(Dial_entities)
        Dial_entities.setTabOrder(self.le_context, self.le_type)
        Dial_entities.setTabOrder(self.le_type, self.le_code)
        Dial_entities.setTabOrder(self.le_code, self.le_name)
        Dial_entities.setTabOrder(self.le_name, self.pb_save)
        Dial_entities.setTabOrder(self.pb_save, self.pb_cancel)

    def retranslateUi(self, Dial_entities):
        Dial_entities.setWindowTitle(_translate("Dial_entities", "Entities Dialog", None))
        self.pb_save.setText(_translate("Dial_entities", "Save", None))
        self.pb_cancel.setText(_translate("Dial_entities", "cancel", None))
        self.l_name.setText(_translate("Dial_entities", "Name:", None))
        self.l_type.setText(_translate("Dial_entities", "Type:", None))
        self.l_message.setText(_translate("Dial_entities", "Edit Entity", None))
        self.l_context.setText(_translate("Dial_entities", "Context:", None))
        self.l_code.setText(_translate("Dial_entities", "Code:", None))

