# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\appli\grapher\gui\src\grapher.ui'
#
# Created: Sat Aug 15 21:30:16 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mwGrapher(object):
    def setupUi(self, mwGrapher):
        mwGrapher.setObjectName(_fromUtf8("mwGrapher"))
        mwGrapher.resize(1001, 773)
        self.centralwidget = QtGui.QWidget(mwGrapher)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.vfGraphZone = QtGui.QFrame(self.splitter)
        self.vfGraphZone.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vfGraphZone.setObjectName(_fromUtf8("vfGraphZone"))
        self.vlGraphZone = QtGui.QVBoxLayout(self.vfGraphZone)
        self.vlGraphZone.setSpacing(0)
        self.vlGraphZone.setMargin(0)
        self.vlGraphZone.setObjectName(_fromUtf8("vlGraphZone"))
        self.vfNodeEditor = QtGui.QFrame(self.splitter)
        self.vfNodeEditor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vfNodeEditor.setObjectName(_fromUtf8("vfNodeEditor"))
        self.vlNodeEditor = QtGui.QVBoxLayout(self.vfNodeEditor)
        self.vlNodeEditor.setSpacing(0)
        self.vlNodeEditor.setMargin(0)
        self.vlNodeEditor.setObjectName(_fromUtf8("vlNodeEditor"))
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        mwGrapher.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mwGrapher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.mGraph = QtGui.QMenu(self.menubar)
        self.mGraph.setObjectName(_fromUtf8("mGraph"))
        self.mCreateNode = QtGui.QMenu(self.mGraph)
        self.mCreateNode.setTearOffEnabled(False)
        self.mCreateNode.setObjectName(_fromUtf8("mCreateNode"))
        self.mFoldUnfold = QtGui.QMenu(self.mGraph)
        self.mFoldUnfold.setObjectName(_fromUtf8("mFoldUnfold"))
        self.mCopyPaste = QtGui.QMenu(self.mGraph)
        self.mCopyPaste.setObjectName(_fromUtf8("mCopyPaste"))
        self.mMoveUpDown = QtGui.QMenu(self.mGraph)
        self.mMoveUpDown.setObjectName(_fromUtf8("mMoveUpDown"))
        self.mFiles = QtGui.QMenu(self.menubar)
        self.mFiles.setObjectName(_fromUtf8("mFiles"))
        self.mDisplay = QtGui.QMenu(self.menubar)
        self.mDisplay.setObjectName(_fromUtf8("mDisplay"))
        self.mToolsBarOrient = QtGui.QMenu(self.mDisplay)
        self.mToolsBarOrient.setObjectName(_fromUtf8("mToolsBarOrient"))
        self.mToolsTabOrient = QtGui.QMenu(self.mDisplay)
        self.mToolsTabOrient.setObjectName(_fromUtf8("mToolsTabOrient"))
        self.mHelp = QtGui.QMenu(self.menubar)
        self.mHelp.setObjectName(_fromUtf8("mHelp"))
        mwGrapher.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mwGrapher)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mwGrapher.setStatusBar(self.statusbar)
        self.tbTools = QtGui.QToolBar(mwGrapher)
        self.tbTools.setMovable(True)
        self.tbTools.setFloatable(False)
        self.tbTools.setObjectName(_fromUtf8("tbTools"))
        mwGrapher.addToolBar(QtCore.Qt.LeftToolBarArea, self.tbTools)
        self.miNewNode = QtGui.QAction(mwGrapher)
        self.miNewNode.setObjectName(_fromUtf8("miNewNode"))
        self.miModul = QtGui.QAction(mwGrapher)
        self.miModul.setObjectName(_fromUtf8("miModul"))
        self.miLoop = QtGui.QAction(mwGrapher)
        self.miLoop.setObjectName(_fromUtf8("miLoop"))
        self.miSysData = QtGui.QAction(mwGrapher)
        self.miSysData.setObjectName(_fromUtf8("miSysData"))
        self.miCmdData = QtGui.QAction(mwGrapher)
        self.miCmdData.setObjectName(_fromUtf8("miCmdData"))
        self.miPyData = QtGui.QAction(mwGrapher)
        self.miPyData.setObjectName(_fromUtf8("miPyData"))
        self.miCondition = QtGui.QAction(mwGrapher)
        self.miCondition.setObjectName(_fromUtf8("miCondition"))
        self.miUnselectAll = QtGui.QAction(mwGrapher)
        self.miUnselectAll.setObjectName(_fromUtf8("miUnselectAll"))
        self.miToolsIconOnly = QtGui.QAction(mwGrapher)
        self.miToolsIconOnly.setCheckable(True)
        self.miToolsIconOnly.setChecked(True)
        self.miToolsIconOnly.setObjectName(_fromUtf8("miToolsIconOnly"))
        self.miBarHorizontal = QtGui.QAction(mwGrapher)
        self.miBarHorizontal.setObjectName(_fromUtf8("miBarHorizontal"))
        self.miBarVertical = QtGui.QAction(mwGrapher)
        self.miBarVertical.setObjectName(_fromUtf8("miBarVertical"))
        self.miTabNorth = QtGui.QAction(mwGrapher)
        self.miTabNorth.setObjectName(_fromUtf8("miTabNorth"))
        self.miTabSouth = QtGui.QAction(mwGrapher)
        self.miTabSouth.setObjectName(_fromUtf8("miTabSouth"))
        self.miTabWest = QtGui.QAction(mwGrapher)
        self.miTabWest.setObjectName(_fromUtf8("miTabWest"))
        self.miTabEast = QtGui.QAction(mwGrapher)
        self.miTabEast.setObjectName(_fromUtf8("miTabEast"))
        self.miToolsVisibility = QtGui.QAction(mwGrapher)
        self.miToolsVisibility.setCheckable(True)
        self.miToolsVisibility.setChecked(True)
        self.miToolsVisibility.setObjectName(_fromUtf8("miToolsVisibility"))
        self.miExpandAll = QtGui.QAction(mwGrapher)
        self.miExpandAll.setObjectName(_fromUtf8("miExpandAll"))
        self.miCollapseAll = QtGui.QAction(mwGrapher)
        self.miCollapseAll.setObjectName(_fromUtf8("miCollapseAll"))
        self.miExpandBranch = QtGui.QAction(mwGrapher)
        self.miExpandBranch.setObjectName(_fromUtf8("miExpandBranch"))
        self.miCollapseBranch = QtGui.QAction(mwGrapher)
        self.miCollapseBranch.setObjectName(_fromUtf8("miCollapseBranch"))
        self.miDelSel = QtGui.QAction(mwGrapher)
        self.miDelSel.setObjectName(_fromUtf8("miDelSel"))
        self.miTreeDict = QtGui.QAction(mwGrapher)
        self.miTreeDict.setObjectName(_fromUtf8("miTreeDict"))
        self.miRefresh = QtGui.QAction(mwGrapher)
        self.miRefresh.setObjectName(_fromUtf8("miRefresh"))
        self.miMoveUp = QtGui.QAction(mwGrapher)
        self.miMoveUp.setObjectName(_fromUtf8("miMoveUp"))
        self.miMoveDn = QtGui.QAction(mwGrapher)
        self.miMoveDn.setObjectName(_fromUtf8("miMoveDn"))
        self.miNodeEditor = QtGui.QAction(mwGrapher)
        self.miNodeEditor.setCheckable(True)
        self.miNodeEditor.setObjectName(_fromUtf8("miNodeEditor"))
        self.miCopyNodes = QtGui.QAction(mwGrapher)
        self.miCopyNodes.setObjectName(_fromUtf8("miCopyNodes"))
        self.miCopyBranch = QtGui.QAction(mwGrapher)
        self.miCopyBranch.setObjectName(_fromUtf8("miCopyBranch"))
        self.miPaste = QtGui.QAction(mwGrapher)
        self.miPaste.setObjectName(_fromUtf8("miPaste"))
        self.miCutBranch = QtGui.QAction(mwGrapher)
        self.miCutBranch.setObjectName(_fromUtf8("miCutBranch"))
        self.miGraphView = QtGui.QAction(mwGrapher)
        self.miGraphView.setCheckable(True)
        self.miGraphView.setObjectName(_fromUtf8("miGraphView"))
        self.miFoldUnfold = QtGui.QAction(mwGrapher)
        self.miFoldUnfold.setObjectName(_fromUtf8("miFoldUnfold"))
        self.miExpandAllEnable = QtGui.QAction(mwGrapher)
        self.miExpandAllEnable.setObjectName(_fromUtf8("miExpandAllEnable"))
        self.miExpandAllDisabled = QtGui.QAction(mwGrapher)
        self.miExpandAllDisabled.setObjectName(_fromUtf8("miExpandAllDisabled"))
        self.miCollapseAllEnabled = QtGui.QAction(mwGrapher)
        self.miCollapseAllEnabled.setObjectName(_fromUtf8("miCollapseAllEnabled"))
        self.miCollapseAllDisabled = QtGui.QAction(mwGrapher)
        self.miCollapseAllDisabled.setObjectName(_fromUtf8("miCollapseAllDisabled"))
        self.miExpandSel = QtGui.QAction(mwGrapher)
        self.miExpandSel.setObjectName(_fromUtf8("miExpandSel"))
        self.miCollapseSel = QtGui.QAction(mwGrapher)
        self.miCollapseSel.setObjectName(_fromUtf8("miCollapseSel"))
        self.mCreateNode.addAction(self.miNewNode)
        self.mCreateNode.addSeparator()
        self.mCreateNode.addAction(self.miModul)
        self.mCreateNode.addAction(self.miSysData)
        self.mCreateNode.addAction(self.miCmdData)
        self.mCreateNode.addAction(self.miPyData)
        self.mCreateNode.addSeparator()
        self.mCreateNode.addAction(self.miLoop)
        self.mCreateNode.addAction(self.miCondition)
        self.mFoldUnfold.addAction(self.miFoldUnfold)
        self.mFoldUnfold.addSeparator()
        self.mFoldUnfold.addAction(self.miExpandSel)
        self.mFoldUnfold.addAction(self.miExpandBranch)
        self.mFoldUnfold.addAction(self.miExpandAllEnable)
        self.mFoldUnfold.addAction(self.miExpandAll)
        self.mFoldUnfold.addSeparator()
        self.mFoldUnfold.addAction(self.miCollapseSel)
        self.mFoldUnfold.addAction(self.miCollapseBranch)
        self.mFoldUnfold.addAction(self.miCollapseAllEnabled)
        self.mFoldUnfold.addAction(self.miCollapseAll)
        self.mCopyPaste.addAction(self.miCopyNodes)
        self.mCopyPaste.addAction(self.miCopyBranch)
        self.mCopyPaste.addSeparator()
        self.mCopyPaste.addAction(self.miCutBranch)
        self.mCopyPaste.addSeparator()
        self.mCopyPaste.addAction(self.miPaste)
        self.mMoveUpDown.addAction(self.miMoveUp)
        self.mMoveUpDown.addAction(self.miMoveDn)
        self.mGraph.addAction(self.miRefresh)
        self.mGraph.addAction(self.miUnselectAll)
        self.mGraph.addSeparator()
        self.mGraph.addAction(self.mCreateNode.menuAction())
        self.mGraph.addAction(self.mFoldUnfold.menuAction())
        self.mGraph.addAction(self.mCopyPaste.menuAction())
        self.mGraph.addAction(self.mMoveUpDown.menuAction())
        self.mGraph.addSeparator()
        self.mGraph.addAction(self.miDelSel)
        self.mToolsBarOrient.addAction(self.miBarHorizontal)
        self.mToolsBarOrient.addAction(self.miBarVertical)
        self.mToolsTabOrient.addAction(self.miTabNorth)
        self.mToolsTabOrient.addAction(self.miTabSouth)
        self.mToolsTabOrient.addAction(self.miTabWest)
        self.mToolsTabOrient.addAction(self.miTabEast)
        self.mDisplay.addAction(self.miNodeEditor)
        self.mDisplay.addAction(self.miGraphView)
        self.mDisplay.addSeparator()
        self.mDisplay.addAction(self.miToolsVisibility)
        self.mDisplay.addAction(self.mToolsBarOrient.menuAction())
        self.mDisplay.addAction(self.mToolsTabOrient.menuAction())
        self.mDisplay.addAction(self.miToolsIconOnly)
        self.mHelp.addAction(self.miTreeDict)
        self.menubar.addAction(self.mFiles.menuAction())
        self.menubar.addAction(self.mGraph.menuAction())
        self.menubar.addAction(self.mDisplay.menuAction())
        self.menubar.addAction(self.mHelp.menuAction())

        self.retranslateUi(mwGrapher)
        QtCore.QMetaObject.connectSlotsByName(mwGrapher)

    def retranslateUi(self, mwGrapher):
        mwGrapher.setWindowTitle(_translate("mwGrapher", "Grapher", None))
        self.mGraph.setTitle(_translate("mwGrapher", "Graph", None))
        self.mCreateNode.setTitle(_translate("mwGrapher", "Create Node", None))
        self.mFoldUnfold.setTitle(_translate("mwGrapher", "Fold / Unfold", None))
        self.mCopyPaste.setTitle(_translate("mwGrapher", "Copy / Paste", None))
        self.mMoveUpDown.setTitle(_translate("mwGrapher", "Move Up / Down", None))
        self.mFiles.setTitle(_translate("mwGrapher", "Files", None))
        self.mDisplay.setTitle(_translate("mwGrapher", "Display", None))
        self.mToolsBarOrient.setTitle(_translate("mwGrapher", "Tools Bar Orient", None))
        self.mToolsTabOrient.setTitle(_translate("mwGrapher", "Tools Tab Orient", None))
        self.mHelp.setTitle(_translate("mwGrapher", "Help", None))
        self.tbTools.setWindowTitle(_translate("mwGrapher", "toolBar", None))
        self.miNewNode.setText(_translate("mwGrapher", "New Node", None))
        self.miModul.setText(_translate("mwGrapher", "Modul", None))
        self.miLoop.setText(_translate("mwGrapher", "Loop", None))
        self.miSysData.setText(_translate("mwGrapher", "SysData", None))
        self.miCmdData.setText(_translate("mwGrapher", "CmdData", None))
        self.miPyData.setText(_translate("mwGrapher", "PyData", None))
        self.miCondition.setText(_translate("mwGrapher", "Condition", None))
        self.miUnselectAll.setText(_translate("mwGrapher", "Unselect All", None))
        self.miToolsIconOnly.setText(_translate("mwGrapher", "Tools Icon Only", None))
        self.miBarHorizontal.setText(_translate("mwGrapher", "Horizontal", None))
        self.miBarVertical.setText(_translate("mwGrapher", "Vertical", None))
        self.miTabNorth.setText(_translate("mwGrapher", "North", None))
        self.miTabSouth.setText(_translate("mwGrapher", "South", None))
        self.miTabWest.setText(_translate("mwGrapher", "West", None))
        self.miTabEast.setText(_translate("mwGrapher", "East", None))
        self.miToolsVisibility.setText(_translate("mwGrapher", "Tools Visibility", None))
        self.miExpandAll.setText(_translate("mwGrapher", "Expand All", None))
        self.miCollapseAll.setText(_translate("mwGrapher", "Collapse All", None))
        self.miExpandBranch.setText(_translate("mwGrapher", "Expand Branch", None))
        self.miCollapseBranch.setText(_translate("mwGrapher", "Collapse Branch", None))
        self.miDelSel.setText(_translate("mwGrapher", "Delete Selected", None))
        self.miTreeDict.setText(_translate("mwGrapher", "Print Tree Dict", None))
        self.miRefresh.setText(_translate("mwGrapher", "Refresh", None))
        self.miMoveUp.setText(_translate("mwGrapher", "Move Up", None))
        self.miMoveDn.setText(_translate("mwGrapher", "Move Down", None))
        self.miNodeEditor.setText(_translate("mwGrapher", "Node Editor", None))
        self.miCopyNodes.setText(_translate("mwGrapher", "Copy Nodes", None))
        self.miCopyBranch.setText(_translate("mwGrapher", "Copy Branch", None))
        self.miPaste.setText(_translate("mwGrapher", "Paste", None))
        self.miCutBranch.setText(_translate("mwGrapher", "Cut Branch", None))
        self.miGraphView.setText(_translate("mwGrapher", "Graph View", None))
        self.miFoldUnfold.setText(_translate("mwGrapher", "Fold / Unfold", None))
        self.miExpandAllEnable.setText(_translate("mwGrapher", "Expand All Enabled", None))
        self.miExpandAllDisabled.setText(_translate("mwGrapher", "Expand All Disabled", None))
        self.miCollapseAllEnabled.setText(_translate("mwGrapher", "Collapse All Enabled", None))
        self.miCollapseAllDisabled.setText(_translate("mwGrapher", "Collapse All Disabled", None))
        self.miExpandSel.setText(_translate("mwGrapher", "Expand Selected", None))
        self.miCollapseSel.setText(_translate("mwGrapher", "Collapse Selected", None))

