# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\tools\maya\cloth\clothEditor\ui\dialSaveFile.ui'
#
# Created: Mon Apr 27 02:38:31 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialSaveFile(object):
    def setupUi(self, dialSaveFile):
        dialSaveFile.setObjectName(_fromUtf8("dialSaveFile"))
        dialSaveFile.resize(323, 166)
        self.gridLayout = QtGui.QGridLayout(dialSaveFile)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_2 = QtGui.QFrame(dialSaveFile)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 1)
        self.line_3 = QtGui.QFrame(dialSaveFile)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 1)
        self.lTitle = QtGui.QLabel(dialSaveFile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lTitle.setFont(font)
        self.lTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lTitle.setObjectName(_fromUtf8("lTitle"))
        self.gridLayout.addWidget(self.lTitle, 0, 0, 1, 1)
        self.line = QtGui.QFrame(dialSaveFile)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.line_4 = QtGui.QFrame(dialSaveFile)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 9, 0, 1, 1)
        self.hlAbsPath = QtGui.QHBoxLayout()
        self.hlAbsPath.setSpacing(2)
        self.hlAbsPath.setContentsMargins(2, -1, 2, -1)
        self.hlAbsPath.setObjectName(_fromUtf8("hlAbsPath"))
        self.lAbsPath = QtGui.QLabel(dialSaveFile)
        self.lAbsPath.setMinimumSize(QtCore.QSize(70, 0))
        self.lAbsPath.setObjectName(_fromUtf8("lAbsPath"))
        self.hlAbsPath.addWidget(self.lAbsPath)
        self.lAbsPathVal = QtGui.QLabel(dialSaveFile)
        self.lAbsPathVal.setObjectName(_fromUtf8("lAbsPathVal"))
        self.hlAbsPath.addWidget(self.lAbsPathVal)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlAbsPath.addItem(spacerItem)
        self.gridLayout.addLayout(self.hlAbsPath, 8, 0, 1, 1)
        self.hlFileName = QtGui.QHBoxLayout()
        self.hlFileName.setSpacing(2)
        self.hlFileName.setContentsMargins(2, -1, 2, -1)
        self.hlFileName.setObjectName(_fromUtf8("hlFileName"))
        self.lFileName = QtGui.QLabel(dialSaveFile)
        self.lFileName.setMinimumSize(QtCore.QSize(70, 0))
        self.lFileName.setObjectName(_fromUtf8("lFileName"))
        self.hlFileName.addWidget(self.lFileName)
        self.lFileNameVal = QtGui.QLabel(dialSaveFile)
        self.lFileNameVal.setObjectName(_fromUtf8("lFileNameVal"))
        self.hlFileName.addWidget(self.lFileNameVal)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlFileName.addItem(spacerItem1)
        self.gridLayout.addLayout(self.hlFileName, 7, 0, 1, 1)
        self.hlRootPath = QtGui.QHBoxLayout()
        self.hlRootPath.setSpacing(2)
        self.hlRootPath.setContentsMargins(2, -1, 2, -1)
        self.hlRootPath.setObjectName(_fromUtf8("hlRootPath"))
        self.lRootPath = QtGui.QLabel(dialSaveFile)
        self.lRootPath.setMinimumSize(QtCore.QSize(70, 0))
        self.lRootPath.setObjectName(_fromUtf8("lRootPath"))
        self.hlRootPath.addWidget(self.lRootPath)
        self.lRootPathVal = QtGui.QLabel(dialSaveFile)
        self.lRootPathVal.setObjectName(_fromUtf8("lRootPathVal"))
        self.hlRootPath.addWidget(self.lRootPathVal)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlRootPath.addItem(spacerItem2)
        self.gridLayout.addLayout(self.hlRootPath, 2, 0, 1, 1)
        self.hlFilePath = QtGui.QHBoxLayout()
        self.hlFilePath.setSpacing(2)
        self.hlFilePath.setContentsMargins(2, -1, 2, -1)
        self.hlFilePath.setObjectName(_fromUtf8("hlFilePath"))
        self.lFilePath = QtGui.QLabel(dialSaveFile)
        self.lFilePath.setMinimumSize(QtCore.QSize(70, 0))
        self.lFilePath.setObjectName(_fromUtf8("lFilePath"))
        self.hlFilePath.addWidget(self.lFilePath)
        self.lFilePathVal = QtGui.QLabel(dialSaveFile)
        self.lFilePathVal.setObjectName(_fromUtf8("lFilePathVal"))
        self.hlFilePath.addWidget(self.lFilePathVal)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlFilePath.addItem(spacerItem3)
        self.gridLayout.addLayout(self.hlFilePath, 3, 0, 1, 1)
        self.hlFileNameEdit = QtGui.QHBoxLayout()
        self.hlFileNameEdit.setSpacing(2)
        self.hlFileNameEdit.setContentsMargins(2, -1, 2, -1)
        self.hlFileNameEdit.setObjectName(_fromUtf8("hlFileNameEdit"))
        self.lFileNameEdit = QtGui.QLabel(dialSaveFile)
        self.lFileNameEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.lFileNameEdit.setObjectName(_fromUtf8("lFileNameEdit"))
        self.hlFileNameEdit.addWidget(self.lFileNameEdit)
        self.leFileNameEdit = QtGui.QLineEdit(dialSaveFile)
        self.leFileNameEdit.setObjectName(_fromUtf8("leFileNameEdit"))
        self.hlFileNameEdit.addWidget(self.leFileNameEdit)
        self.gridLayout.addLayout(self.hlFileNameEdit, 5, 0, 1, 1)
        self.hlEditBtns = QtGui.QHBoxLayout()
        self.hlEditBtns.setSpacing(2)
        self.hlEditBtns.setContentsMargins(2, -1, 2, -1)
        self.hlEditBtns.setObjectName(_fromUtf8("hlEditBtns"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlEditBtns.addItem(spacerItem4)
        self.pbSave = QtGui.QPushButton(dialSaveFile)
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.hlEditBtns.addWidget(self.pbSave)
        self.pbCancel = QtGui.QPushButton(dialSaveFile)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.hlEditBtns.addWidget(self.pbCancel)
        self.gridLayout.addLayout(self.hlEditBtns, 10, 0, 1, 1)

        self.retranslateUi(dialSaveFile)
        QtCore.QMetaObject.connectSlotsByName(dialSaveFile)

    def retranslateUi(self, dialSaveFile):
        dialSaveFile.setWindowTitle(_translate("dialSaveFile", "Save File", None))
        self.lTitle.setText(_translate("dialSaveFile", "Save", None))
        self.lAbsPath.setText(_translate("dialSaveFile", "File Full Path: ", None))
        self.lAbsPathVal.setText(_translate("dialSaveFile", "TextLabel", None))
        self.lFileName.setText(_translate("dialSaveFile", "File Full Name: ", None))
        self.lFileNameVal.setText(_translate("dialSaveFile", "TextLabel", None))
        self.lRootPath.setText(_translate("dialSaveFile", "Root Path: ", None))
        self.lRootPathVal.setText(_translate("dialSaveFile", "TextLabel", None))
        self.lFilePath.setText(_translate("dialSaveFile", "File Path: ", None))
        self.lFilePathVal.setText(_translate("dialSaveFile", "TextLabel", None))
        self.lFileNameEdit.setText(_translate("dialSaveFile", "File Name: ", None))
        self.pbSave.setText(_translate("dialSaveFile", "Save", None))
        self.pbCancel.setText(_translate("dialSaveFile", "Cancel", None))

