# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\tools\maya\cloth\clothEditor\ui\wgFiles.ui'
#
# Created: Fri May 01 11:24:41 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_wgFiles(object):
    def setupUi(self, wgFiles):
        wgFiles.setObjectName(_fromUtf8("wgFiles"))
        wgFiles.resize(389, 284)
        self.gridLayout = QtGui.QGridLayout(wgFiles)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_2 = QtGui.QFrame(wgFiles)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 1)
        self.line = QtGui.QFrame(wgFiles)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 6, 0, 1, 1)
        self.line_4 = QtGui.QFrame(wgFiles)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 4, 0, 1, 1)
        self.hlEditBtns = QtGui.QHBoxLayout()
        self.hlEditBtns.setObjectName(_fromUtf8("hlEditBtns"))
        self.pbLoad = QtGui.QPushButton(wgFiles)
        self.pbLoad.setObjectName(_fromUtf8("pbLoad"))
        self.hlEditBtns.addWidget(self.pbLoad)
        self.pbSave = QtGui.QPushButton(wgFiles)
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.hlEditBtns.addWidget(self.pbSave)
        self.gridLayout.addLayout(self.hlEditBtns, 8, 0, 1, 1)
        self.line_3 = QtGui.QFrame(wgFiles)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 0, 1, 1)
        self.hlEditRoot = QtGui.QHBoxLayout()
        self.hlEditRoot.setSpacing(2)
        self.hlEditRoot.setContentsMargins(0, 0, -1, 0)
        self.hlEditRoot.setObjectName(_fromUtf8("hlEditRoot"))
        self.pbNewProject = QtGui.QPushButton(wgFiles)
        self.pbNewProject.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbNewProject.setObjectName(_fromUtf8("pbNewProject"))
        self.hlEditRoot.addWidget(self.pbNewProject)
        self.pbNewFolder = QtGui.QPushButton(wgFiles)
        self.pbNewFolder.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbNewFolder.setObjectName(_fromUtf8("pbNewFolder"))
        self.hlEditRoot.addWidget(self.pbNewFolder)
        self.pbRefresh = QtGui.QPushButton(wgFiles)
        self.pbRefresh.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbRefresh.setObjectName(_fromUtf8("pbRefresh"))
        self.hlEditRoot.addWidget(self.pbRefresh)
        self.gridLayout.addLayout(self.hlEditRoot, 3, 0, 1, 1)
        self.hlFilesRootPath = QtGui.QHBoxLayout()
        self.hlFilesRootPath.setSpacing(2)
        self.hlFilesRootPath.setContentsMargins(2, -1, 2, -1)
        self.hlFilesRootPath.setObjectName(_fromUtf8("hlFilesRootPath"))
        self.lRootPath = QtGui.QLabel(wgFiles)
        self.lRootPath.setMinimumSize(QtCore.QSize(80, 0))
        self.lRootPath.setMaximumSize(QtCore.QSize(80, 20))
        self.lRootPath.setObjectName(_fromUtf8("lRootPath"))
        self.hlFilesRootPath.addWidget(self.lRootPath)
        self.lRootPathVal = QtGui.QLabel(wgFiles)
        self.lRootPathVal.setObjectName(_fromUtf8("lRootPathVal"))
        self.hlFilesRootPath.addWidget(self.lRootPathVal)
        self.gridLayout.addLayout(self.hlFilesRootPath, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(wgFiles)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.twDir = QtGui.QTreeWidget(self.splitter)
        self.twDir.setIndentation(15)
        self.twDir.setObjectName(_fromUtf8("twDir"))
        self.twDir.headerItem().setText(0, _fromUtf8("1"))
        self.twDir.header().setVisible(False)
        self.twFiles = QtGui.QTreeWidget(self.splitter)
        self.twFiles.setIndentation(2)
        self.twFiles.setItemsExpandable(False)
        self.twFiles.setExpandsOnDoubleClick(False)
        self.twFiles.setObjectName(_fromUtf8("twFiles"))
        self.twFiles.headerItem().setText(0, _fromUtf8("1"))
        self.twFiles.header().setVisible(False)
        self.gridLayout.addWidget(self.splitter, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.qfVtxMode = QtGui.QFrame(wgFiles)
        self.qfVtxMode.setMaximumSize(QtCore.QSize(16777215, 24))
        self.qfVtxMode.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfVtxMode.setObjectName(_fromUtf8("qfVtxMode"))
        self.hlVtxMode = QtGui.QHBoxLayout(self.qfVtxMode)
        self.hlVtxMode.setSpacing(12)
        self.hlVtxMode.setContentsMargins(2, 0, 2, 0)
        self.hlVtxMode.setObjectName(_fromUtf8("hlVtxMode"))
        self.lVtxMode = QtGui.QLabel(self.qfVtxMode)
        self.lVtxMode.setMinimumSize(QtCore.QSize(70, 0))
        self.lVtxMode.setMaximumSize(QtCore.QSize(70, 20))
        self.lVtxMode.setObjectName(_fromUtf8("lVtxMode"))
        self.hlVtxMode.addWidget(self.lVtxMode)
        self.cbAll = QtGui.QCheckBox(self.qfVtxMode)
        self.cbAll.setChecked(True)
        self.cbAll.setObjectName(_fromUtf8("cbAll"))
        self.bgVtxMode = QtGui.QButtonGroup(wgFiles)
        self.bgVtxMode.setObjectName(_fromUtf8("bgVtxMode"))
        self.bgVtxMode.addButton(self.cbAll)
        self.hlVtxMode.addWidget(self.cbAll)
        self.cbSel = QtGui.QCheckBox(self.qfVtxMode)
        self.cbSel.setObjectName(_fromUtf8("cbSel"))
        self.bgVtxMode.addButton(self.cbSel)
        self.hlVtxMode.addWidget(self.cbSel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlVtxMode.addItem(spacerItem1)
        self.gridLayout.addWidget(self.qfVtxMode, 7, 0, 1, 1)

        self.retranslateUi(wgFiles)
        QtCore.QMetaObject.connectSlotsByName(wgFiles)

    def retranslateUi(self, wgFiles):
        wgFiles.setWindowTitle(_translate("wgFiles", "Files", None))
        self.pbLoad.setText(_translate("wgFiles", "Load", None))
        self.pbSave.setText(_translate("wgFiles", "Save", None))
        self.pbNewProject.setText(_translate("wgFiles", "New Project", None))
        self.pbNewFolder.setText(_translate("wgFiles", "New Folder", None))
        self.pbRefresh.setText(_translate("wgFiles", "Refresh", None))
        self.lRootPath.setText(_translate("wgFiles", "Files Root Path:", None))
        self.lRootPathVal.setText(_translate("wgFiles", "Root Path Not Set", None))
        self.lVtxMode.setText(_translate("wgFiles", "VtxMap Mode: ", None))
        self.cbAll.setText(_translate("wgFiles", "All Vtx Maps", None))
        self.cbSel.setText(_translate("wgFiles", "Selected Vtx Map", None))

