# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\appli\grapher\ui\nodeEditor.ui'
#
# Created: Tue Nov 25 01:42:24 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_nodeEditor(object):
    def setupUi(self, nodeEditor):
        nodeEditor.setObjectName(_fromUtf8("nodeEditor"))
        nodeEditor.resize(573, 800)
        self.gridLayout = QtGui.QGridLayout(nodeEditor)
        self.gridLayout.setMargin(1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hlNodeName = QtGui.QHBoxLayout()
        self.hlNodeName.setSpacing(4)
        self.hlNodeName.setObjectName(_fromUtf8("hlNodeName"))
        self.lName = QtGui.QLabel(nodeEditor)
        self.lName.setMinimumSize(QtCore.QSize(40, 0))
        self.lName.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lName.setObjectName(_fromUtf8("lName"))
        self.hlNodeName.addWidget(self.lName)
        self.leNodeName = QtGui.QLineEdit(nodeEditor)
        self.leNodeName.setMinimumSize(QtCore.QSize(150, 0))
        self.leNodeName.setReadOnly(True)
        self.leNodeName.setObjectName(_fromUtf8("leNodeName"))
        self.hlNodeName.addWidget(self.leNodeName)
        self.lType = QtGui.QLabel(nodeEditor)
        self.lType.setMinimumSize(QtCore.QSize(40, 0))
        self.lType.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lType.setObjectName(_fromUtf8("lType"))
        self.hlNodeName.addWidget(self.lType)
        self.cbNodeType = QtGui.QComboBox(nodeEditor)
        self.cbNodeType.setMinimumSize(QtCore.QSize(70, 18))
        self.cbNodeType.setMaximumSize(QtCore.QSize(40, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cbNodeType.setFont(font)
        self.cbNodeType.setObjectName(_fromUtf8("cbNodeType"))
        self.cbNodeType.addItem(_fromUtf8(""))
        self.cbNodeType.addItem(_fromUtf8(""))
        self.cbNodeType.addItem(_fromUtf8(""))
        self.cbNodeType.addItem(_fromUtf8(""))
        self.cbNodeType.addItem(_fromUtf8(""))
        self.hlNodeName.addWidget(self.cbNodeType)
        self.gridLayout.addLayout(self.hlNodeName, 0, 0, 1, 1)
        self.hlNodeVersion = QtGui.QHBoxLayout()
        self.hlNodeVersion.setSpacing(4)
        self.hlNodeVersion.setObjectName(_fromUtf8("hlNodeVersion"))
        self.lVTitle = QtGui.QLabel(nodeEditor)
        self.lVTitle.setMinimumSize(QtCore.QSize(40, 0))
        self.lVTitle.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lVTitle.setObjectName(_fromUtf8("lVTitle"))
        self.hlNodeVersion.addWidget(self.lVTitle)
        self.leVersionTitle = QtGui.QLineEdit(nodeEditor)
        self.leVersionTitle.setMinimumSize(QtCore.QSize(0, 18))
        self.leVersionTitle.setMaximumSize(QtCore.QSize(16777215, 18))
        self.leVersionTitle.setObjectName(_fromUtf8("leVersionTitle"))
        self.hlNodeVersion.addWidget(self.leVersionTitle)
        self.lVersion = QtGui.QLabel(nodeEditor)
        self.lVersion.setMinimumSize(QtCore.QSize(40, 0))
        self.lVersion.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lVersion.setObjectName(_fromUtf8("lVersion"))
        self.hlNodeVersion.addWidget(self.lVersion)
        self.cbNodeVersion = QtGui.QComboBox(nodeEditor)
        self.cbNodeVersion.setMinimumSize(QtCore.QSize(60, 18))
        self.cbNodeVersion.setMaximumSize(QtCore.QSize(60, 18))
        self.cbNodeVersion.setSizeIncrement(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cbNodeVersion.setFont(font)
        self.cbNodeVersion.setObjectName(_fromUtf8("cbNodeVersion"))
        self.hlNodeVersion.addWidget(self.cbNodeVersion)
        self.bNewVersion = QtGui.QPushButton(nodeEditor)
        self.bNewVersion.setMinimumSize(QtCore.QSize(35, 18))
        self.bNewVersion.setMaximumSize(QtCore.QSize(35, 18))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.bNewVersion.setFont(font)
        self.bNewVersion.setObjectName(_fromUtf8("bNewVersion"))
        self.hlNodeVersion.addWidget(self.bNewVersion)
        self.bDelVersion = QtGui.QPushButton(nodeEditor)
        self.bDelVersion.setMinimumSize(QtCore.QSize(35, 18))
        self.bDelVersion.setMaximumSize(QtCore.QSize(35, 18))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.bDelVersion.setFont(font)
        self.bDelVersion.setObjectName(_fromUtf8("bDelVersion"))
        self.hlNodeVersion.addWidget(self.bDelVersion)
        self.gridLayout.addLayout(self.hlNodeVersion, 1, 0, 1, 1)
        self.line_4 = QtGui.QFrame(nodeEditor)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 2, 0, 1, 1)
        self.splitter = QtGui.QSplitter(nodeEditor)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.flComment = QtGui.QFrame(self.splitter)
        self.flComment.setFrameShape(QtGui.QFrame.StyledPanel)
        self.flComment.setObjectName(_fromUtf8("flComment"))
        self.vlComment = QtGui.QVBoxLayout(self.flComment)
        self.vlComment.setSpacing(0)
        self.vlComment.setMargin(0)
        self.vlComment.setObjectName(_fromUtf8("vlComment"))
        self.cbComment = QtGui.QCheckBox(self.flComment)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.cbComment.setFont(font)
        self.cbComment.setCheckable(True)
        self.cbComment.setChecked(False)
        self.cbComment.setObjectName(_fromUtf8("cbComment"))
        self.vlComment.addWidget(self.cbComment)
        self.flVariables = QtGui.QFrame(self.splitter)
        self.flVariables.setFrameShape(QtGui.QFrame.StyledPanel)
        self.flVariables.setObjectName(_fromUtf8("flVariables"))
        self.vlVariables = QtGui.QVBoxLayout(self.flVariables)
        self.vlVariables.setSpacing(0)
        self.vlVariables.setMargin(0)
        self.vlVariables.setObjectName(_fromUtf8("vlVariables"))
        self.cbVariables = QtGui.QCheckBox(self.flVariables)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.cbVariables.setFont(font)
        self.cbVariables.setChecked(False)
        self.cbVariables.setObjectName(_fromUtf8("cbVariables"))
        self.vlVariables.addWidget(self.cbVariables)
        self.flExecNode = QtGui.QFrame(self.splitter)
        self.flExecNode.setMaximumSize(QtCore.QSize(16777215, 25))
        self.flExecNode.setFrameShape(QtGui.QFrame.StyledPanel)
        self.flExecNode.setObjectName(_fromUtf8("flExecNode"))
        self.vlExecNode = QtGui.QVBoxLayout(self.flExecNode)
        self.vlExecNode.setSpacing(0)
        self.vlExecNode.setMargin(0)
        self.vlExecNode.setObjectName(_fromUtf8("vlExecNode"))
        self.cbExecNode = QtGui.QCheckBox(self.flExecNode)
        self.cbExecNode.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbExecNode.setObjectName(_fromUtf8("cbExecNode"))
        self.vlExecNode.addWidget(self.cbExecNode)
        self.qfLoop = QtGui.QFrame(self.splitter)
        self.qfLoop.setMaximumSize(QtCore.QSize(16777215, 70))
        self.qfLoop.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfLoop.setObjectName(_fromUtf8("qfLoop"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.qfLoop)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lLoop = QtGui.QLabel(self.qfLoop)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lLoop.setFont(font)
        self.lLoop.setObjectName(_fromUtf8("lLoop"))
        self.verticalLayout_6.addWidget(self.lLoop)
        self.hlLoopOption = QtGui.QHBoxLayout()
        self.hlLoopOption.setSpacing(1)
        self.hlLoopOption.setObjectName(_fromUtf8("hlLoopOption"))
        self.rbLoopRange = QtGui.QRadioButton(self.qfLoop)
        self.rbLoopRange.setChecked(True)
        self.rbLoopRange.setObjectName(_fromUtf8("rbLoopRange"))
        self.bgLoopType = QtGui.QButtonGroup(nodeEditor)
        self.bgLoopType.setObjectName(_fromUtf8("bgLoopType"))
        self.bgLoopType.addButton(self.rbLoopRange)
        self.hlLoopOption.addWidget(self.rbLoopRange)
        self.rbLoopList = QtGui.QRadioButton(self.qfLoop)
        self.rbLoopList.setObjectName(_fromUtf8("rbLoopList"))
        self.bgLoopType.addButton(self.rbLoopList)
        self.hlLoopOption.addWidget(self.rbLoopList)
        self.rbLoopSingle = QtGui.QRadioButton(self.qfLoop)
        self.rbLoopSingle.setObjectName(_fromUtf8("rbLoopSingle"))
        self.bgLoopType.addButton(self.rbLoopSingle)
        self.hlLoopOption.addWidget(self.rbLoopSingle)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlLoopOption.addItem(spacerItem)
        self.lLoopIter = QtGui.QLabel(self.qfLoop)
        self.lLoopIter.setObjectName(_fromUtf8("lLoopIter"))
        self.hlLoopOption.addWidget(self.lLoopIter)
        self.leLoopIter = QtGui.QLineEdit(self.qfLoop)
        self.leLoopIter.setMinimumSize(QtCore.QSize(60, 0))
        self.leLoopIter.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leLoopIter.setAlignment(QtCore.Qt.AlignCenter)
        self.leLoopIter.setObjectName(_fromUtf8("leLoopIter"))
        self.hlLoopOption.addWidget(self.leLoopIter)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlLoopOption.addItem(spacerItem1)
        self.lLoopCheckFile = QtGui.QLabel(self.qfLoop)
        self.lLoopCheckFile.setObjectName(_fromUtf8("lLoopCheckFile"))
        self.hlLoopOption.addWidget(self.lLoopCheckFile)
        self.leLoopCheckFile = QtGui.QLineEdit(self.qfLoop)
        self.leLoopCheckFile.setMinimumSize(QtCore.QSize(100, 0))
        self.leLoopCheckFile.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leLoopCheckFile.setObjectName(_fromUtf8("leLoopCheckFile"))
        self.hlLoopOption.addWidget(self.leLoopCheckFile)
        self.verticalLayout_6.addLayout(self.hlLoopOption)
        self.qfLoopRange = QtGui.QFrame(self.qfLoop)
        self.qfLoopRange.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfLoopRange.setObjectName(_fromUtf8("qfLoopRange"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.qfLoopRange)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lLoopRange = QtGui.QLabel(self.qfLoopRange)
        self.lLoopRange.setMinimumSize(QtCore.QSize(50, 0))
        self.lLoopRange.setObjectName(_fromUtf8("lLoopRange"))
        self.horizontalLayout_7.addWidget(self.lLoopRange)
        self.lRangeStart = QtGui.QLabel(self.qfLoopRange)
        self.lRangeStart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lRangeStart.setObjectName(_fromUtf8("lRangeStart"))
        self.horizontalLayout_7.addWidget(self.lRangeStart)
        self.leRangeStart = QtGui.QLineEdit(self.qfLoopRange)
        self.leRangeStart.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leRangeStart.setObjectName(_fromUtf8("leRangeStart"))
        self.horizontalLayout_7.addWidget(self.leRangeStart)
        spacerItem2 = QtGui.QSpacerItem(25, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.lRangeStop = QtGui.QLabel(self.qfLoopRange)
        self.lRangeStop.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lRangeStop.setObjectName(_fromUtf8("lRangeStop"))
        self.horizontalLayout_7.addWidget(self.lRangeStop)
        self.leRangeStop = QtGui.QLineEdit(self.qfLoopRange)
        self.leRangeStop.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leRangeStop.setObjectName(_fromUtf8("leRangeStop"))
        self.horizontalLayout_7.addWidget(self.leRangeStop)
        spacerItem3 = QtGui.QSpacerItem(25, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.lRangeStep = QtGui.QLabel(self.qfLoopRange)
        self.lRangeStep.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lRangeStep.setObjectName(_fromUtf8("lRangeStep"))
        self.horizontalLayout_7.addWidget(self.lRangeStep)
        self.leRangeStep = QtGui.QLineEdit(self.qfLoopRange)
        self.leRangeStep.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leRangeStep.setObjectName(_fromUtf8("leRangeStep"))
        self.horizontalLayout_7.addWidget(self.leRangeStep)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_6.addWidget(self.qfLoopRange)
        self.qfLoopList = QtGui.QFrame(self.qfLoop)
        self.qfLoopList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfLoopList.setObjectName(_fromUtf8("qfLoopList"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.qfLoopList)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lLoopList = QtGui.QLabel(self.qfLoopList)
        self.lLoopList.setMinimumSize(QtCore.QSize(50, 0))
        self.lLoopList.setObjectName(_fromUtf8("lLoopList"))
        self.horizontalLayout_8.addWidget(self.lLoopList)
        self.leLoopList = QtGui.QLineEdit(self.qfLoopList)
        self.leLoopList.setObjectName(_fromUtf8("leLoopList"))
        self.horizontalLayout_8.addWidget(self.leLoopList)
        self.verticalLayout_6.addWidget(self.qfLoopList)
        self.qfLoopSingle = QtGui.QFrame(self.qfLoop)
        self.qfLoopSingle.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfLoopSingle.setObjectName(_fromUtf8("qfLoopSingle"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.qfLoopSingle)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lLoopSingle = QtGui.QLabel(self.qfLoopSingle)
        self.lLoopSingle.setMinimumSize(QtCore.QSize(50, 0))
        self.lLoopSingle.setObjectName(_fromUtf8("lLoopSingle"))
        self.horizontalLayout_9.addWidget(self.lLoopSingle)
        self.leLoopSingle = QtGui.QLineEdit(self.qfLoopSingle)
        self.leLoopSingle.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leLoopSingle.setObjectName(_fromUtf8("leLoopSingle"))
        self.horizontalLayout_9.addWidget(self.leLoopSingle)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_6.addWidget(self.qfLoopSingle)
        self.qfScript = QtGui.QFrame(self.splitter)
        self.qfScript.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfScript.setObjectName(_fromUtf8("qfScript"))
        self.vlScript = QtGui.QVBoxLayout(self.qfScript)
        self.vlScript.setSpacing(0)
        self.vlScript.setMargin(0)
        self.vlScript.setObjectName(_fromUtf8("vlScript"))
        self.qfCmd = QtGui.QFrame(self.qfScript)
        self.qfCmd.setMaximumSize(QtCore.QSize(16777215, 30))
        self.qfCmd.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfCmd.setObjectName(_fromUtf8("qfCmd"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.qfCmd)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lCmd = QtGui.QLabel(self.qfCmd)
        self.lCmd.setMinimumSize(QtCore.QSize(40, 0))
        self.lCmd.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lCmd.setSizeIncrement(QtCore.QSize(0, 0))
        self.lCmd.setObjectName(_fromUtf8("lCmd"))
        self.horizontalLayout_3.addWidget(self.lCmd)
        self.leCmd = QtGui.QLineEdit(self.qfCmd)
        self.leCmd.setObjectName(_fromUtf8("leCmd"))
        self.horizontalLayout_3.addWidget(self.leCmd)
        self.vlScript.addWidget(self.qfCmd)
        self.hlScriptButton = QtGui.QHBoxLayout()
        self.hlScriptButton.setSpacing(0)
        self.hlScriptButton.setObjectName(_fromUtf8("hlScriptButton"))
        self.leScript = QtGui.QLabel(self.qfScript)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.leScript.setFont(font)
        self.leScript.setObjectName(_fromUtf8("leScript"))
        self.hlScriptButton.addWidget(self.leScript)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlScriptButton.addItem(spacerItem6)
        self.bExtern = QtGui.QPushButton(self.qfScript)
        self.bExtern.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.bExtern.setFont(font)
        self.bExtern.setObjectName(_fromUtf8("bExtern"))
        self.hlScriptButton.addWidget(self.bExtern)
        self.bUpdate = QtGui.QPushButton(self.qfScript)
        self.bUpdate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.bUpdate.setFont(font)
        self.bUpdate.setObjectName(_fromUtf8("bUpdate"))
        self.hlScriptButton.addWidget(self.bUpdate)
        self.vlScript.addLayout(self.hlScriptButton)
        self.qfScriptSpacer = QtGui.QFrame(self.splitter)
        self.qfScriptSpacer.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfScriptSpacer.setObjectName(_fromUtf8("qfScriptSpacer"))
        self.verticalLayout = QtGui.QVBoxLayout(self.qfScriptSpacer)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setMargin(1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem7 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.flTrash = QtGui.QFrame(self.splitter)
        self.flTrash.setFrameShape(QtGui.QFrame.StyledPanel)
        self.flTrash.setObjectName(_fromUtf8("flTrash"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.flTrash)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cbTrash = QtGui.QCheckBox(self.flTrash)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.cbTrash.setFont(font)
        self.cbTrash.setCheckable(True)
        self.cbTrash.setChecked(False)
        self.cbTrash.setObjectName(_fromUtf8("cbTrash"))
        self.verticalLayout_5.addWidget(self.cbTrash)
        self.teTrash = QtGui.QTextEdit(self.flTrash)
        self.teTrash.setObjectName(_fromUtf8("teTrash"))
        self.verticalLayout_5.addWidget(self.teTrash)
        self.gridLayout.addWidget(self.splitter, 3, 0, 1, 1)
        self.line_5 = QtGui.QFrame(nodeEditor)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 4, 0, 1, 1)
        self.hlNodeBtns = QtGui.QHBoxLayout()
        self.hlNodeBtns.setSpacing(1)
        self.hlNodeBtns.setObjectName(_fromUtf8("hlNodeBtns"))
        self.bClose = QtGui.QPushButton(nodeEditor)
        self.bClose.setMinimumSize(QtCore.QSize(60, 20))
        self.bClose.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bClose.setObjectName(_fromUtf8("bClose"))
        self.hlNodeBtns.addWidget(self.bClose)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlNodeBtns.addItem(spacerItem8)
        self.bSave = QtGui.QPushButton(nodeEditor)
        self.bSave.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.hlNodeBtns.addWidget(self.bSave)
        self.bCancel = QtGui.QPushButton(nodeEditor)
        self.bCancel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bCancel.setObjectName(_fromUtf8("bCancel"))
        self.hlNodeBtns.addWidget(self.bCancel)
        self.gridLayout.addLayout(self.hlNodeBtns, 5, 0, 1, 1)

        self.retranslateUi(nodeEditor)
        QtCore.QMetaObject.connectSlotsByName(nodeEditor)

    def retranslateUi(self, nodeEditor):
        nodeEditor.setWindowTitle(_translate("nodeEditor", "Node Editor", None))
        self.lName.setText(_translate("nodeEditor", "Name: ", None))
        self.lType.setText(_translate("nodeEditor", "Type:", None))
        self.cbNodeType.setItemText(0, _translate("nodeEditor", "modul", None))
        self.cbNodeType.setItemText(1, _translate("nodeEditor", "loop", None))
        self.cbNodeType.setItemText(2, _translate("nodeEditor", "sysData", None))
        self.cbNodeType.setItemText(3, _translate("nodeEditor", "cmdData", None))
        self.cbNodeType.setItemText(4, _translate("nodeEditor", "purData", None))
        self.lVTitle.setText(_translate("nodeEditor", "Title: ", None))
        self.lVersion.setText(_translate("nodeEditor", "Version:", None))
        self.bNewVersion.setText(_translate("nodeEditor", "New", None))
        self.bDelVersion.setText(_translate("nodeEditor", "Del", None))
        self.cbComment.setText(_translate("nodeEditor", "Comment", None))
        self.cbVariables.setText(_translate("nodeEditor", "Variables", None))
        self.cbExecNode.setText(_translate("nodeEditor", "Exec Node", None))
        self.lLoop.setText(_translate("nodeEditor", "Loop", None))
        self.rbLoopRange.setText(_translate("nodeEditor", "Range", None))
        self.rbLoopList.setText(_translate("nodeEditor", "List", None))
        self.rbLoopSingle.setText(_translate("nodeEditor", "Single", None))
        self.lLoopIter.setText(_translate("nodeEditor", "Iterator: ", None))
        self.leLoopIter.setText(_translate("nodeEditor", "i", None))
        self.lLoopCheckFile.setText(_translate("nodeEditor", "CheckFile: ", None))
        self.leLoopCheckFile.setText(_translate("nodeEditor", "tmpCheck", None))
        self.lLoopRange.setText(_translate("nodeEditor", "Range : ", None))
        self.lRangeStart.setText(_translate("nodeEditor", "Start = ", None))
        self.leRangeStart.setText(_translate("nodeEditor", "1", None))
        self.lRangeStop.setText(_translate("nodeEditor", "Stop = ", None))
        self.leRangeStop.setText(_translate("nodeEditor", "100", None))
        self.lRangeStep.setText(_translate("nodeEditor", "Step = ", None))
        self.leRangeStep.setText(_translate("nodeEditor", "1", None))
        self.lLoopList.setText(_translate("nodeEditor", "List : ", None))
        self.lLoopSingle.setText(_translate("nodeEditor", "Single : ", None))
        self.lCmd.setText(_translate("nodeEditor", "cmd:", None))
        self.leScript.setText(_translate("nodeEditor", "Script", None))
        self.bExtern.setText(_translate("nodeEditor", "Extern", None))
        self.bUpdate.setText(_translate("nodeEditor", "Update", None))
        self.cbTrash.setText(_translate("nodeEditor", "Trash", None))
        self.bClose.setText(_translate("nodeEditor", "Close", None))
        self.bSave.setText(_translate("nodeEditor", "Save", None))
        self.bCancel.setText(_translate("nodeEditor", "Cancel", None))

