# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\appli\fondation\gui\fondation\settings\_src\userGroups.ui'
#
# Created: Sun Dec 06 19:13:17 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_wg_tsUserGroups(object):
    def setupUi(self, wg_tsUserGroups):
        wg_tsUserGroups.setObjectName(_fromUtf8("wg_tsUserGroups"))
        wg_tsUserGroups.resize(574, 800)
        self.gridLayout = QtGui.QGridLayout(wg_tsUserGroups)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.qf_userGroups = QtGui.QFrame(wg_tsUserGroups)
        self.qf_userGroups.setMinimumSize(QtCore.QSize(0, 0))
        self.qf_userGroups.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qf_userGroups.setObjectName(_fromUtf8("qf_userGroups"))
        self.vl_userGroups = QtGui.QVBoxLayout(self.qf_userGroups)
        self.vl_userGroups.setSpacing(0)
        self.vl_userGroups.setMargin(0)
        self.vl_userGroups.setObjectName(_fromUtf8("vl_userGroups"))
        self.l_groups = QtGui.QLabel(self.qf_userGroups)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l_groups.setFont(font)
        self.l_groups.setObjectName(_fromUtf8("l_groups"))
        self.vl_userGroups.addWidget(self.l_groups)
        self.hl_groups = QtGui.QHBoxLayout()
        self.hl_groups.setSpacing(0)
        self.hl_groups.setObjectName(_fromUtf8("hl_groups"))
        self.vl_groupsEdit = QtGui.QVBoxLayout()
        self.vl_groupsEdit.setSpacing(6)
        self.vl_groupsEdit.setContentsMargins(-1, 26, -1, -1)
        self.vl_groupsEdit.setObjectName(_fromUtf8("vl_groupsEdit"))
        self.hl_moveGrp = QtGui.QHBoxLayout()
        self.hl_moveGrp.setSpacing(0)
        self.hl_moveGrp.setObjectName(_fromUtf8("hl_moveGrp"))
        self.pb_upGrp = QtGui.QPushButton(self.qf_userGroups)
        self.pb_upGrp.setMinimumSize(QtCore.QSize(22, 22))
        self.pb_upGrp.setMaximumSize(QtCore.QSize(22, 22))
        self.pb_upGrp.setText(_fromUtf8(""))
        self.pb_upGrp.setObjectName(_fromUtf8("pb_upGrp"))
        self.hl_moveGrp.addWidget(self.pb_upGrp)
        self.pb_dnGrp = QtGui.QPushButton(self.qf_userGroups)
        self.pb_dnGrp.setMinimumSize(QtCore.QSize(22, 22))
        self.pb_dnGrp.setMaximumSize(QtCore.QSize(22, 22))
        self.pb_dnGrp.setText(_fromUtf8(""))
        self.pb_dnGrp.setObjectName(_fromUtf8("pb_dnGrp"))
        self.hl_moveGrp.addWidget(self.pb_dnGrp)
        self.vl_groupsEdit.addLayout(self.hl_moveGrp)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vl_groupsEdit.addItem(spacerItem)
        self.pb_addGrp = QtGui.QPushButton(self.qf_userGroups)
        self.pb_addGrp.setMaximumSize(QtCore.QSize(55, 20))
        self.pb_addGrp.setToolTip(_fromUtf8(""))
        self.pb_addGrp.setObjectName(_fromUtf8("pb_addGrp"))
        self.vl_groupsEdit.addWidget(self.pb_addGrp)
        self.pb_delGrp = QtGui.QPushButton(self.qf_userGroups)
        self.pb_delGrp.setMaximumSize(QtCore.QSize(55, 20))
        self.pb_delGrp.setToolTip(_fromUtf8(""))
        self.pb_delGrp.setObjectName(_fromUtf8("pb_delGrp"))
        self.vl_groupsEdit.addWidget(self.pb_delGrp)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vl_groupsEdit.addItem(spacerItem1)
        self.pb_editGrp = QtGui.QPushButton(self.qf_userGroups)
        self.pb_editGrp.setMaximumSize(QtCore.QSize(55, 20))
        self.pb_editGrp.setToolTip(_fromUtf8(""))
        self.pb_editGrp.setObjectName(_fromUtf8("pb_editGrp"))
        self.vl_groupsEdit.addWidget(self.pb_editGrp)
        self.pb_styleGrp = QtGui.QPushButton(self.qf_userGroups)
        self.pb_styleGrp.setMaximumSize(QtCore.QSize(55, 20))
        self.pb_styleGrp.setToolTip(_fromUtf8(""))
        self.pb_styleGrp.setObjectName(_fromUtf8("pb_styleGrp"))
        self.vl_groupsEdit.addWidget(self.pb_styleGrp)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vl_groupsEdit.addItem(spacerItem2)
        self.hl_groups.addLayout(self.vl_groupsEdit)
        self.line = QtGui.QFrame(self.qf_userGroups)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.hl_groups.addWidget(self.line)
        self.tw_groups = QtGui.QTreeWidget(self.qf_userGroups)
        self.tw_groups.setAlternatingRowColors(True)
        self.tw_groups.setIndentation(0)
        self.tw_groups.setItemsExpandable(False)
        self.tw_groups.setExpandsOnDoubleClick(False)
        self.tw_groups.setObjectName(_fromUtf8("tw_groups"))
        self.tw_groups.headerItem().setText(0, _fromUtf8("Code"))
        self.tw_groups.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_groups.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_groups.headerItem().setTextAlignment(2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_groups.header().setStretchLastSection(False)
        self.hl_groups.addWidget(self.tw_groups)
        self.vl_userGroups.addLayout(self.hl_groups)
        self.line_2 = QtGui.QFrame(self.qf_userGroups)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.vl_userGroups.addWidget(self.line_2)
        self.hl_grpApply = QtGui.QHBoxLayout()
        self.hl_grpApply.setSpacing(0)
        self.hl_grpApply.setObjectName(_fromUtf8("hl_grpApply"))
        self.pb_grpApply = QtGui.QPushButton(self.qf_userGroups)
        self.pb_grpApply.setMaximumSize(QtCore.QSize(60, 20))
        self.pb_grpApply.setObjectName(_fromUtf8("pb_grpApply"))
        self.hl_grpApply.addWidget(self.pb_grpApply)
        self.pb_grpCancel = QtGui.QPushButton(self.qf_userGroups)
        self.pb_grpCancel.setMaximumSize(QtCore.QSize(60, 20))
        self.pb_grpCancel.setObjectName(_fromUtf8("pb_grpCancel"))
        self.hl_grpApply.addWidget(self.pb_grpCancel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_grpApply.addItem(spacerItem3)
        self.vl_userGroups.addLayout(self.hl_grpApply)
        self.gridLayout.addWidget(self.qf_userGroups, 0, 0, 1, 1)
        self.qf_users = QtGui.QFrame(wg_tsUserGroups)
        self.qf_users.setMinimumSize(QtCore.QSize(0, 0))
        self.qf_users.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qf_users.setObjectName(_fromUtf8("qf_users"))
        self.vl_users = QtGui.QVBoxLayout(self.qf_users)
        self.vl_users.setSpacing(0)
        self.vl_users.setMargin(0)
        self.vl_users.setObjectName(_fromUtf8("vl_users"))
        self.l_users = QtGui.QLabel(self.qf_users)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l_users.setFont(font)
        self.l_users.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l_users.setObjectName(_fromUtf8("l_users"))
        self.vl_users.addWidget(self.l_users)
        self.line_5 = QtGui.QFrame(self.qf_users)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.vl_users.addWidget(self.line_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.vl_usersEdit = QtGui.QVBoxLayout()
        self.vl_usersEdit.setSpacing(6)
        self.vl_usersEdit.setContentsMargins(-1, 26, -1, -1)
        self.vl_usersEdit.setObjectName(_fromUtf8("vl_usersEdit"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vl_usersEdit.addItem(spacerItem4)
        self.pb_addUser = QtGui.QPushButton(self.qf_users)
        self.pb_addUser.setMaximumSize(QtCore.QSize(55, 20))
        self.pb_addUser.setToolTip(_fromUtf8(""))
        self.pb_addUser.setObjectName(_fromUtf8("pb_addUser"))
        self.vl_usersEdit.addWidget(self.pb_addUser)
        self.pb_delUser = QtGui.QPushButton(self.qf_users)
        self.pb_delUser.setMaximumSize(QtCore.QSize(55, 20))
        self.pb_delUser.setToolTip(_fromUtf8(""))
        self.pb_delUser.setObjectName(_fromUtf8("pb_delUser"))
        self.vl_usersEdit.addWidget(self.pb_delUser)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vl_usersEdit.addItem(spacerItem5)
        self.pb_editUser = QtGui.QPushButton(self.qf_users)
        self.pb_editUser.setMaximumSize(QtCore.QSize(55, 20))
        self.pb_editUser.setToolTip(_fromUtf8(""))
        self.pb_editUser.setObjectName(_fromUtf8("pb_editUser"))
        self.vl_usersEdit.addWidget(self.pb_editUser)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vl_usersEdit.addItem(spacerItem6)
        self.horizontalLayout.addLayout(self.vl_usersEdit)
        self.line_3 = QtGui.QFrame(self.qf_users)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.tw_users = QtGui.QTreeWidget(self.qf_users)
        self.tw_users.setObjectName(_fromUtf8("tw_users"))
        self.tw_users.headerItem().setText(0, _fromUtf8("Icone"))
        self.tw_users.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_users.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_users.headerItem().setTextAlignment(2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_users.headerItem().setTextAlignment(3, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.horizontalLayout.addWidget(self.tw_users)
        self.vl_users.addLayout(self.horizontalLayout)
        self.line_4 = QtGui.QFrame(self.qf_users)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.vl_users.addWidget(self.line_4)
        self.hl_userApply = QtGui.QHBoxLayout()
        self.hl_userApply.setSpacing(0)
        self.hl_userApply.setObjectName(_fromUtf8("hl_userApply"))
        self.pb_userApply = QtGui.QPushButton(self.qf_users)
        self.pb_userApply.setMaximumSize(QtCore.QSize(60, 20))
        self.pb_userApply.setObjectName(_fromUtf8("pb_userApply"))
        self.hl_userApply.addWidget(self.pb_userApply)
        self.pb_userCancel = QtGui.QPushButton(self.qf_users)
        self.pb_userCancel.setMaximumSize(QtCore.QSize(60, 20))
        self.pb_userCancel.setObjectName(_fromUtf8("pb_userCancel"))
        self.hl_userApply.addWidget(self.pb_userCancel)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_userApply.addItem(spacerItem7)
        self.vl_users.addLayout(self.hl_userApply)
        self.gridLayout.addWidget(self.qf_users, 1, 0, 1, 1)

        self.retranslateUi(wg_tsUserGroups)
        QtCore.QMetaObject.connectSlotsByName(wg_tsUserGroups)
        wg_tsUserGroups.setTabOrder(self.pb_upGrp, self.pb_dnGrp)
        wg_tsUserGroups.setTabOrder(self.pb_dnGrp, self.pb_addGrp)
        wg_tsUserGroups.setTabOrder(self.pb_addGrp, self.pb_delGrp)
        wg_tsUserGroups.setTabOrder(self.pb_delGrp, self.pb_editGrp)
        wg_tsUserGroups.setTabOrder(self.pb_editGrp, self.pb_styleGrp)
        wg_tsUserGroups.setTabOrder(self.pb_styleGrp, self.tw_groups)

    def retranslateUi(self, wg_tsUserGroups):
        wg_tsUserGroups.setWindowTitle(_translate("wg_tsUserGroups", "User Groups", None))
        self.l_groups.setText(_translate("wg_tsUserGroups", "User Groups:", None))
        self.pb_addGrp.setText(_translate("wg_tsUserGroups", "Add", None))
        self.pb_delGrp.setText(_translate("wg_tsUserGroups", "Del", None))
        self.pb_editGrp.setText(_translate("wg_tsUserGroups", "Edit", None))
        self.pb_styleGrp.setText(_translate("wg_tsUserGroups", "Style", None))
        self.tw_groups.headerItem().setText(1, _translate("wg_tsUserGroups", "Name", None))
        self.tw_groups.headerItem().setText(2, _translate("wg_tsUserGroups", "Style", None))
        self.pb_grpApply.setText(_translate("wg_tsUserGroups", "Apply", None))
        self.pb_grpCancel.setText(_translate("wg_tsUserGroups", "Cancel", None))
        self.l_users.setText(_translate("wg_tsUserGroups", "Users:", None))
        self.pb_addUser.setText(_translate("wg_tsUserGroups", "Add", None))
        self.pb_delUser.setText(_translate("wg_tsUserGroups", "Del", None))
        self.pb_editUser.setText(_translate("wg_tsUserGroups", "Edit", None))
        self.tw_users.headerItem().setText(1, _translate("wg_tsUserGroups", "User Name", None))
        self.tw_users.headerItem().setText(2, _translate("wg_tsUserGroups", "First Name", None))
        self.tw_users.headerItem().setText(3, _translate("wg_tsUserGroups", "Last Name", None))
        self.pb_userApply.setText(_translate("wg_tsUserGroups", "Apply", None))
        self.pb_userCancel.setText(_translate("wg_tsUserGroups", "Cancel", None))

