# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\appli\userManager\ui\userEditor.ui'
#
# Created: Tue Oct 28 12:19:48 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_userEditor(object):
    def setupUi(self, userEditor):
        userEditor.setObjectName(_fromUtf8("userEditor"))
        userEditor.resize(410, 166)
        self.glUserEditor = QtGui.QGridLayout(userEditor)
        self.glUserEditor.setMargin(0)
        self.glUserEditor.setSpacing(0)
        self.glUserEditor.setObjectName(_fromUtf8("glUserEditor"))
        self.hlAlias = QtGui.QHBoxLayout()
        self.hlAlias.setSpacing(2)
        self.hlAlias.setContentsMargins(4, -1, 4, -1)
        self.hlAlias.setObjectName(_fromUtf8("hlAlias"))
        self.lAlias = QtGui.QLabel(userEditor)
        self.lAlias.setMinimumSize(QtCore.QSize(60, 0))
        self.lAlias.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lAlias.setObjectName(_fromUtf8("lAlias"))
        self.hlAlias.addWidget(self.lAlias)
        self.leAlias = QtGui.QLineEdit(userEditor)
        self.leAlias.setObjectName(_fromUtf8("leAlias"))
        self.hlAlias.addWidget(self.leAlias)
        self.glUserEditor.addLayout(self.hlAlias, 3, 0, 1, 1)
        self.hlName = QtGui.QHBoxLayout()
        self.hlName.setSpacing(2)
        self.hlName.setContentsMargins(4, -1, 4, -1)
        self.hlName.setObjectName(_fromUtf8("hlName"))
        self.lName = QtGui.QLabel(userEditor)
        self.lName.setMinimumSize(QtCore.QSize(60, 0))
        self.lName.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lName.setObjectName(_fromUtf8("lName"))
        self.hlName.addWidget(self.lName)
        self.leName = QtGui.QLineEdit(userEditor)
        self.leName.setObjectName(_fromUtf8("leName"))
        self.hlName.addWidget(self.leName)
        self.glUserEditor.addLayout(self.hlName, 1, 0, 1, 1)
        self.hlPhoto = QtGui.QHBoxLayout()
        self.hlPhoto.setSpacing(2)
        self.hlPhoto.setContentsMargins(4, -1, 4, -1)
        self.hlPhoto.setObjectName(_fromUtf8("hlPhoto"))
        self.lPhoto = QtGui.QLabel(userEditor)
        self.lPhoto.setMinimumSize(QtCore.QSize(60, 0))
        self.lPhoto.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lPhoto.setObjectName(_fromUtf8("lPhoto"))
        self.hlPhoto.addWidget(self.lPhoto)
        self.lePhoto = QtGui.QLineEdit(userEditor)
        self.lePhoto.setObjectName(_fromUtf8("lePhoto"))
        self.hlPhoto.addWidget(self.lePhoto)
        self.bOpenPhoto = QtGui.QPushButton(userEditor)
        self.bOpenPhoto.setObjectName(_fromUtf8("bOpenPhoto"))
        self.hlPhoto.addWidget(self.bOpenPhoto)
        self.glUserEditor.addLayout(self.hlPhoto, 4, 0, 1, 1)
        self.hlLogo = QtGui.QHBoxLayout()
        self.hlLogo.setSpacing(2)
        self.hlLogo.setContentsMargins(4, -1, 4, -1)
        self.hlLogo.setObjectName(_fromUtf8("hlLogo"))
        self.lLogo = QtGui.QLabel(userEditor)
        self.lLogo.setMinimumSize(QtCore.QSize(60, 0))
        self.lLogo.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lLogo.setObjectName(_fromUtf8("lLogo"))
        self.hlLogo.addWidget(self.lLogo)
        self.leLogo = QtGui.QLineEdit(userEditor)
        self.leLogo.setObjectName(_fromUtf8("leLogo"))
        self.hlLogo.addWidget(self.leLogo)
        self.bOpenLogo = QtGui.QPushButton(userEditor)
        self.bOpenLogo.setObjectName(_fromUtf8("bOpenLogo"))
        self.hlLogo.addWidget(self.bOpenLogo)
        self.glUserEditor.addLayout(self.hlLogo, 5, 0, 1, 1)
        self.hlUserGrp = QtGui.QHBoxLayout()
        self.hlUserGrp.setSpacing(2)
        self.hlUserGrp.setContentsMargins(4, -1, 4, -1)
        self.hlUserGrp.setObjectName(_fromUtf8("hlUserGrp"))
        self.lUserGrp = QtGui.QLabel(userEditor)
        self.lUserGrp.setMinimumSize(QtCore.QSize(60, 0))
        self.lUserGrp.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lUserGrp.setObjectName(_fromUtf8("lUserGrp"))
        self.hlUserGrp.addWidget(self.lUserGrp)
        self.cbUserGrp = QtGui.QComboBox(userEditor)
        self.cbUserGrp.setMinimumSize(QtCore.QSize(60, 0))
        self.cbUserGrp.setMaximumSize(QtCore.QSize(60, 16777215))
        self.cbUserGrp.setMaxVisibleItems(12)
        self.cbUserGrp.setObjectName(_fromUtf8("cbUserGrp"))
        self.hlUserGrp.addWidget(self.cbUserGrp)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlUserGrp.addItem(spacerItem)
        self.lStatus = QtGui.QLabel(userEditor)
        self.lStatus.setMinimumSize(QtCore.QSize(60, 0))
        self.lStatus.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lStatus.setObjectName(_fromUtf8("lStatus"))
        self.hlUserGrp.addWidget(self.lStatus)
        self.cbStatus = QtGui.QComboBox(userEditor)
        self.cbStatus.setMinimumSize(QtCore.QSize(60, 0))
        self.cbStatus.setMaximumSize(QtCore.QSize(60, 16777215))
        self.cbStatus.setObjectName(_fromUtf8("cbStatus"))
        self.hlUserGrp.addWidget(self.cbStatus)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlUserGrp.addItem(spacerItem1)
        self.glUserEditor.addLayout(self.hlUserGrp, 6, 0, 1, 1)
        self.line = QtGui.QFrame(userEditor)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.glUserEditor.addWidget(self.line, 7, 0, 1, 1)
        self.hlButtns = QtGui.QHBoxLayout()
        self.hlButtns.setSpacing(2)
        self.hlButtns.setContentsMargins(4, -1, 4, -1)
        self.hlButtns.setObjectName(_fromUtf8("hlButtns"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlButtns.addItem(spacerItem2)
        self.bSave = QtGui.QPushButton(userEditor)
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.hlButtns.addWidget(self.bSave)
        self.bCancel = QtGui.QPushButton(userEditor)
        self.bCancel.setObjectName(_fromUtf8("bCancel"))
        self.hlButtns.addWidget(self.bCancel)
        self.glUserEditor.addLayout(self.hlButtns, 8, 0, 1, 1)
        self.hlFistName = QtGui.QHBoxLayout()
        self.hlFistName.setSpacing(2)
        self.hlFistName.setContentsMargins(4, -1, 4, -1)
        self.hlFistName.setObjectName(_fromUtf8("hlFistName"))
        self.lFirstName = QtGui.QLabel(userEditor)
        self.lFirstName.setMinimumSize(QtCore.QSize(60, 0))
        self.lFirstName.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lFirstName.setObjectName(_fromUtf8("lFirstName"))
        self.hlFistName.addWidget(self.lFirstName)
        self.leFirstName = QtGui.QLineEdit(userEditor)
        self.leFirstName.setObjectName(_fromUtf8("leFirstName"))
        self.hlFistName.addWidget(self.leFirstName)
        self.glUserEditor.addLayout(self.hlFistName, 2, 0, 1, 1)

        self.retranslateUi(userEditor)
        self.cbUserGrp.setCurrentIndex(-1)
        self.cbStatus.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(userEditor)
        userEditor.setTabOrder(self.leName, self.leFirstName)
        userEditor.setTabOrder(self.leFirstName, self.leAlias)
        userEditor.setTabOrder(self.leAlias, self.lePhoto)
        userEditor.setTabOrder(self.lePhoto, self.bOpenPhoto)
        userEditor.setTabOrder(self.bOpenPhoto, self.leLogo)
        userEditor.setTabOrder(self.leLogo, self.bOpenLogo)
        userEditor.setTabOrder(self.bOpenLogo, self.cbUserGrp)
        userEditor.setTabOrder(self.cbUserGrp, self.cbStatus)
        userEditor.setTabOrder(self.cbStatus, self.bSave)
        userEditor.setTabOrder(self.bSave, self.bCancel)

    def retranslateUi(self, userEditor):
        userEditor.setWindowTitle(_translate("userEditor", "User Editor", None))
        self.lAlias.setText(_translate("userEditor", "Alias:", None))
        self.lName.setText(_translate("userEditor", "Name:", None))
        self.lPhoto.setText(_translate("userEditor", "Photo:", None))
        self.bOpenPhoto.setText(_translate("userEditor", "Open", None))
        self.lLogo.setText(_translate("userEditor", "Logo:", None))
        self.bOpenLogo.setText(_translate("userEditor", "Open", None))
        self.lUserGrp.setText(_translate("userEditor", "UserGrp", None))
        self.lStatus.setText(_translate("userEditor", "Status:", None))
        self.bSave.setText(_translate("userEditor", "Save", None))
        self.bCancel.setText(_translate("userEditor", "Cancel", None))
        self.lFirstName.setText(_translate("userEditor", "FirstName:", None))

