# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\appli\grapher\gui\src\wgProjectEdit.ui'
#
# Created: Sun Jun 28 16:10:59 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mwEditProject(object):
    def setupUi(self, mwEditProject):
        mwEditProject.setObjectName(_fromUtf8("mwEditProject"))
        mwEditProject.resize(344, 311)
        self.centralwidget = QtGui.QWidget(mwEditProject)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.qfProject = QtGui.QFrame(self.centralwidget)
        self.qfProject.setLineWidth(0)
        self.qfProject.setObjectName(_fromUtf8("qfProject"))
        self.hlProject_1 = QtGui.QHBoxLayout(self.qfProject)
        self.hlProject_1.setSpacing(2)
        self.hlProject_1.setMargin(0)
        self.hlProject_1.setObjectName(_fromUtf8("hlProject_1"))
        self.lName = QtGui.QLabel(self.qfProject)
        self.lName.setMinimumSize(QtCore.QSize(85, 0))
        self.lName.setMaximumSize(QtCore.QSize(85, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lName.setFont(font)
        self.lName.setObjectName(_fromUtf8("lName"))
        self.hlProject_1.addWidget(self.lName)
        self.lNameValue = QtGui.QLabel(self.qfProject)
        self.lNameValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lNameValue.setObjectName(_fromUtf8("lNameValue"))
        self.hlProject_1.addWidget(self.lNameValue)
        spacerItem = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hlProject_1.addItem(spacerItem)
        self.lAlias = QtGui.QLabel(self.qfProject)
        self.lAlias.setMinimumSize(QtCore.QSize(70, 0))
        self.lAlias.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lAlias.setFont(font)
        self.lAlias.setObjectName(_fromUtf8("lAlias"))
        self.hlProject_1.addWidget(self.lAlias)
        self.lAliasValue = QtGui.QLabel(self.qfProject)
        self.lAliasValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lAliasValue.setObjectName(_fromUtf8("lAliasValue"))
        self.hlProject_1.addWidget(self.lAliasValue)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlProject_1.addItem(spacerItem1)
        self.gridLayout.addWidget(self.qfProject, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.hlSettings = QtGui.QHBoxLayout()
        self.hlSettings.setSpacing(2)
        self.hlSettings.setObjectName(_fromUtf8("hlSettings"))
        self.twSettings = QtGui.QTreeWidget(self.centralwidget)
        self.twSettings.setMaximumSize(QtCore.QSize(110, 16777215))
        self.twSettings.setIndentation(2)
        self.twSettings.setItemsExpandable(False)
        self.twSettings.setExpandsOnDoubleClick(False)
        self.twSettings.setObjectName(_fromUtf8("twSettings"))
        self.twSettings.headerItem().setText(0, _fromUtf8("1"))
        self.twSettings.header().setVisible(False)
        self.hlSettings.addWidget(self.twSettings)
        self.vlSettings = QtGui.QVBoxLayout()
        self.vlSettings.setSpacing(0)
        self.vlSettings.setContentsMargins(-1, 0, -1, -1)
        self.vlSettings.setObjectName(_fromUtf8("vlSettings"))
        self.qfTreeContents = QtGui.QFrame(self.centralwidget)
        self.qfTreeContents.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfTreeContents.setObjectName(_fromUtf8("qfTreeContents"))
        self.vlTreeContents = QtGui.QVBoxLayout(self.qfTreeContents)
        self.vlTreeContents.setSpacing(0)
        self.vlTreeContents.setMargin(0)
        self.vlTreeContents.setObjectName(_fromUtf8("vlTreeContents"))
        self.qfEntity = QtGui.QFrame(self.qfTreeContents)
        self.qfEntity.setObjectName(_fromUtf8("qfEntity"))
        self.hlEntity = QtGui.QHBoxLayout(self.qfEntity)
        self.hlEntity.setSpacing(2)
        self.hlEntity.setContentsMargins(2, 1, 2, 1)
        self.hlEntity.setObjectName(_fromUtf8("hlEntity"))
        self.lEntity = QtGui.QLabel(self.qfEntity)
        self.lEntity.setMinimumSize(QtCore.QSize(70, 0))
        self.lEntity.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lEntity.setObjectName(_fromUtf8("lEntity"))
        self.hlEntity.addWidget(self.lEntity)
        self.cbEntity = QtGui.QComboBox(self.qfEntity)
        self.cbEntity.setObjectName(_fromUtf8("cbEntity"))
        self.hlEntity.addWidget(self.cbEntity)
        self.vlTreeContents.addWidget(self.qfEntity)
        self.qfEntityType = QtGui.QFrame(self.qfTreeContents)
        self.qfEntityType.setObjectName(_fromUtf8("qfEntityType"))
        self.hlEntityType = QtGui.QHBoxLayout(self.qfEntityType)
        self.hlEntityType.setSpacing(2)
        self.hlEntityType.setContentsMargins(2, 1, 2, 1)
        self.hlEntityType.setObjectName(_fromUtf8("hlEntityType"))
        self.lEntityType = QtGui.QLabel(self.qfEntityType)
        self.lEntityType.setMinimumSize(QtCore.QSize(70, 0))
        self.lEntityType.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lEntityType.setObjectName(_fromUtf8("lEntityType"))
        self.hlEntityType.addWidget(self.lEntityType)
        self.cbEntityType = QtGui.QComboBox(self.qfEntityType)
        self.cbEntityType.setObjectName(_fromUtf8("cbEntityType"))
        self.hlEntityType.addWidget(self.cbEntityType)
        self.vlTreeContents.addWidget(self.qfEntityType)
        self.qfEntitySpec = QtGui.QFrame(self.qfTreeContents)
        self.qfEntitySpec.setObjectName(_fromUtf8("qfEntitySpec"))
        self.hlEntityType_2 = QtGui.QHBoxLayout(self.qfEntitySpec)
        self.hlEntityType_2.setSpacing(2)
        self.hlEntityType_2.setContentsMargins(2, 1, 2, 1)
        self.hlEntityType_2.setObjectName(_fromUtf8("hlEntityType_2"))
        self.lEntitySpec = QtGui.QLabel(self.qfEntitySpec)
        self.lEntitySpec.setMinimumSize(QtCore.QSize(70, 0))
        self.lEntitySpec.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lEntitySpec.setObjectName(_fromUtf8("lEntitySpec"))
        self.hlEntityType_2.addWidget(self.lEntitySpec)
        self.cbEntitySpec = QtGui.QComboBox(self.qfEntitySpec)
        self.cbEntitySpec.setObjectName(_fromUtf8("cbEntitySpec"))
        self.hlEntityType_2.addWidget(self.cbEntitySpec)
        self.vlTreeContents.addWidget(self.qfEntitySpec)
        self.line_4 = QtGui.QFrame(self.qfTreeContents)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.vlTreeContents.addWidget(self.line_4)
        self.hlNewFolder = QtGui.QHBoxLayout()
        self.hlNewFolder.setSpacing(2)
        self.hlNewFolder.setContentsMargins(2, 0, 2, -1)
        self.hlNewFolder.setObjectName(_fromUtf8("hlNewFolder"))
        self.lNewFolder = QtGui.QLabel(self.qfTreeContents)
        self.lNewFolder.setMinimumSize(QtCore.QSize(70, 0))
        self.lNewFolder.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lNewFolder.setObjectName(_fromUtf8("lNewFolder"))
        self.hlNewFolder.addWidget(self.lNewFolder)
        self.leNewFolder = QtGui.QLineEdit(self.qfTreeContents)
        self.leNewFolder.setObjectName(_fromUtf8("leNewFolder"))
        self.hlNewFolder.addWidget(self.leNewFolder)
        self.vlTreeContents.addLayout(self.hlNewFolder)
        self.qfAssetNs = QtGui.QFrame(self.qfTreeContents)
        self.qfAssetNs.setObjectName(_fromUtf8("qfAssetNs"))
        self.hlNewNs = QtGui.QHBoxLayout(self.qfAssetNs)
        self.hlNewNs.setSpacing(2)
        self.hlNewNs.setContentsMargins(2, 1, 2, -1)
        self.hlNewNs.setObjectName(_fromUtf8("hlNewNs"))
        self.lAssetNs = QtGui.QLabel(self.qfAssetNs)
        self.lAssetNs.setMinimumSize(QtCore.QSize(70, 0))
        self.lAssetNs.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lAssetNs.setObjectName(_fromUtf8("lAssetNs"))
        self.hlNewNs.addWidget(self.lAssetNs)
        self.leAssetNs = QtGui.QLineEdit(self.qfAssetNs)
        self.leAssetNs.setText(_fromUtf8(""))
        self.leAssetNs.setObjectName(_fromUtf8("leAssetNs"))
        self.hlNewNs.addWidget(self.leAssetNs)
        self.vlTreeContents.addWidget(self.qfAssetNs)
        self.line_3 = QtGui.QFrame(self.qfTreeContents)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.vlTreeContents.addWidget(self.line_3)
        self.hlButtons = QtGui.QHBoxLayout()
        self.hlButtons.setSpacing(0)
        self.hlButtons.setObjectName(_fromUtf8("hlButtons"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlButtons.addItem(spacerItem2)
        self.pbCreate = QtGui.QPushButton(self.qfTreeContents)
        self.pbCreate.setObjectName(_fromUtf8("pbCreate"))
        self.hlButtons.addWidget(self.pbCreate)
        self.pbCancel = QtGui.QPushButton(self.qfTreeContents)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.hlButtons.addWidget(self.pbCancel)
        self.vlTreeContents.addLayout(self.hlButtons)
        self.vlSettings.addWidget(self.qfTreeContents)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlSettings.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.vlSettings.addItem(spacerItem4)
        self.hlSettings.addLayout(self.vlSettings)
        self.gridLayout.addLayout(self.hlSettings, 2, 0, 1, 1)
        mwEditProject.setCentralWidget(self.centralwidget)

        self.retranslateUi(mwEditProject)
        QtCore.QMetaObject.connectSlotsByName(mwEditProject)

    def retranslateUi(self, mwEditProject):
        mwEditProject.setWindowTitle(_translate("mwEditProject", "Settings", None))
        self.lName.setText(_translate("mwEditProject", "Project Name :", None))
        self.lNameValue.setText(_translate("mwEditProject", "TextLabel", None))
        self.lAlias.setText(_translate("mwEditProject", "Project Alias :", None))
        self.lAliasValue.setText(_translate("mwEditProject", "TextLabel", None))
        self.lEntity.setText(_translate("mwEditProject", "Entity :", None))
        self.lEntityType.setText(_translate("mwEditProject", "Entity Type :", None))
        self.lEntitySpec.setText(_translate("mwEditProject", "Entity Spec :", None))
        self.lNewFolder.setText(_translate("mwEditProject", "New Folder :", None))
        self.lAssetNs.setText(_translate("mwEditProject", "Asset Ns :", None))
        self.pbCreate.setText(_translate("mwEditProject", "Create", None))
        self.pbCancel.setText(_translate("mwEditProject", "Cancel", None))

