# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\appli\grapher\ud\grapher.ui'
#
# Created: Thu Jun 18 03:18:45 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mwGrapher(object):
    def setupUi(self, mwGrapher):
        mwGrapher.setObjectName(_fromUtf8("mwGrapher"))
        mwGrapher.resize(1000, 600)
        self.centralwidget = QtGui.QWidget(mwGrapher)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.glGrapher = QtGui.QGridLayout(self.centralwidget)
        self.glGrapher.setMargin(0)
        self.glGrapher.setSpacing(0)
        self.glGrapher.setObjectName(_fromUtf8("glGrapher"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlTree = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlTree.setMargin(0)
        self.vlTree.setObjectName(_fromUtf8("vlTree"))
        self.twTree = QtGui.QTreeWidget(self.verticalLayoutWidget)
        self.twTree.setObjectName(_fromUtf8("twTree"))
        self.twTree.headerItem().setText(0, _fromUtf8("1"))
        self.vlTree.addWidget(self.twTree)
        self.tabGraph = QtGui.QTabWidget(self.splitter)
        self.tabGraph.setTabsClosable(False)
        self.tabGraph.setMovable(True)
        self.tabGraph.setObjectName(_fromUtf8("tabGraph"))
        self.vfNodeData = QtGui.QFrame(self.splitter)
        self.vfNodeData.setObjectName(_fromUtf8("vfNodeData"))
        self.vlNodeData = QtGui.QVBoxLayout(self.vfNodeData)
        self.vlNodeData.setSpacing(0)
        self.vlNodeData.setObjectName(_fromUtf8("vlNodeData"))
        self.twNodeData = QtGui.QTreeWidget(self.vfNodeData)
        self.twNodeData.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.twNodeData.setIndentation(0)
        self.twNodeData.setExpandsOnDoubleClick(False)
        self.twNodeData.setObjectName(_fromUtf8("twNodeData"))
        self.twNodeData.headerItem().setText(0, _fromUtf8("1"))
        self.twNodeData.header().setVisible(False)
        self.vlNodeData.addWidget(self.twNodeData)
        self.glGrapher.addWidget(self.splitter, 0, 0, 1, 1)
        mwGrapher.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mwGrapher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.mPref = QtGui.QMenu(self.menubar)
        self.mPref.setObjectName(_fromUtf8("mPref"))
        self.mToolsBar = QtGui.QMenu(self.mPref)
        self.mToolsBar.setTearOffEnabled(True)
        self.mToolsBar.setObjectName(_fromUtf8("mToolsBar"))
        self.mBarOrientation = QtGui.QMenu(self.mToolsBar)
        self.mBarOrientation.setObjectName(_fromUtf8("mBarOrientation"))
        self.mTabOrientation = QtGui.QMenu(self.mToolsBar)
        self.mTabOrientation.setObjectName(_fromUtf8("mTabOrientation"))
        self.mStyle = QtGui.QMenu(self.mPref)
        self.mStyle.setObjectName(_fromUtf8("mStyle"))
        self.mHelp = QtGui.QMenu(self.menubar)
        self.mHelp.setObjectName(_fromUtf8("mHelp"))
        self.mEdit = QtGui.QMenu(self.menubar)
        self.mEdit.setObjectName(_fromUtf8("mEdit"))
        self.mGrapher = QtGui.QMenu(self.menubar)
        self.mGrapher.setObjectName(_fromUtf8("mGrapher"))
        mwGrapher.setMenuBar(self.menubar)
        self.tbTools = QtGui.QToolBar(mwGrapher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbTools.sizePolicy().hasHeightForWidth())
        self.tbTools.setSizePolicy(sizePolicy)
        self.tbTools.setObjectName(_fromUtf8("tbTools"))
        mwGrapher.addToolBar(QtCore.Qt.RightToolBarArea, self.tbTools)
        self.miNorth2 = QtGui.QAction(mwGrapher)
        self.miNorth2.setObjectName(_fromUtf8("miNorth2"))
        self.miSouth2 = QtGui.QAction(mwGrapher)
        self.miSouth2.setObjectName(_fromUtf8("miSouth2"))
        self.miWest2 = QtGui.QAction(mwGrapher)
        self.miWest2.setObjectName(_fromUtf8("miWest2"))
        self.miEast2 = QtGui.QAction(mwGrapher)
        self.miEast2.setObjectName(_fromUtf8("miEast2"))
        self.miConnectNodes = QtGui.QAction(mwGrapher)
        self.miConnectNodes.setObjectName(_fromUtf8("miConnectNodes"))
        self.miTabNorth = QtGui.QAction(mwGrapher)
        self.miTabNorth.setObjectName(_fromUtf8("miTabNorth"))
        self.miTabSouth = QtGui.QAction(mwGrapher)
        self.miTabSouth.setObjectName(_fromUtf8("miTabSouth"))
        self.miTabWest = QtGui.QAction(mwGrapher)
        self.miTabWest.setObjectName(_fromUtf8("miTabWest"))
        self.miTabEast = QtGui.QAction(mwGrapher)
        self.miTabEast.setObjectName(_fromUtf8("miTabEast"))
        self.miAddGraphZone = QtGui.QAction(mwGrapher)
        self.miAddGraphZone.setObjectName(_fromUtf8("miAddGraphZone"))
        self.miBarHorizontal = QtGui.QAction(mwGrapher)
        self.miBarHorizontal.setObjectName(_fromUtf8("miBarHorizontal"))
        self.miBarVertical = QtGui.QAction(mwGrapher)
        self.miBarVertical.setObjectName(_fromUtf8("miBarVertical"))
        self.miDefaultStyle = QtGui.QAction(mwGrapher)
        self.miDefaultStyle.setObjectName(_fromUtf8("miDefaultStyle"))
        self.miDarkOrange = QtGui.QAction(mwGrapher)
        self.miDarkOrange.setObjectName(_fromUtf8("miDarkOrange"))
        self.miDarkGrey = QtGui.QAction(mwGrapher)
        self.miDarkGrey.setObjectName(_fromUtf8("miDarkGrey"))
        self.miRedGrey = QtGui.QAction(mwGrapher)
        self.miRedGrey.setObjectName(_fromUtf8("miRedGrey"))
        self.miShowToolBar = QtGui.QAction(mwGrapher)
        self.miShowToolBar.setObjectName(_fromUtf8("miShowToolBar"))
        self.miHideToolBar = QtGui.QAction(mwGrapher)
        self.miHideToolBar.setObjectName(_fromUtf8("miHideToolBar"))
        self.miToolBarVisibility = QtGui.QAction(mwGrapher)
        self.miToolBarVisibility.setCheckable(True)
        self.miToolBarVisibility.setChecked(False)
        self.miToolBarVisibility.setObjectName(_fromUtf8("miToolBarVisibility"))
        self.miParamsVisibility = QtGui.QAction(mwGrapher)
        self.miParamsVisibility.setCheckable(True)
        self.miParamsVisibility.setChecked(True)
        self.miParamsVisibility.setObjectName(_fromUtf8("miParamsVisibility"))
        self.mBarOrientation.addAction(self.miBarHorizontal)
        self.mBarOrientation.addAction(self.miBarVertical)
        self.mTabOrientation.addAction(self.miTabNorth)
        self.mTabOrientation.addAction(self.miTabSouth)
        self.mTabOrientation.addAction(self.miTabWest)
        self.mTabOrientation.addAction(self.miTabEast)
        self.mToolsBar.addAction(self.miToolBarVisibility)
        self.mToolsBar.addAction(self.mBarOrientation.menuAction())
        self.mToolsBar.addAction(self.mTabOrientation.menuAction())
        self.mStyle.addAction(self.miDefaultStyle)
        self.mStyle.addAction(self.miDarkOrange)
        self.mStyle.addAction(self.miDarkGrey)
        self.mStyle.addAction(self.miRedGrey)
        self.mPref.addAction(self.mStyle.menuAction())
        self.mPref.addSeparator()
        self.mPref.addAction(self.mToolsBar.menuAction())
        self.mPref.addAction(self.miParamsVisibility)
        self.mEdit.addAction(self.miAddGraphZone)
        self.mEdit.addAction(self.miConnectNodes)
        self.menubar.addAction(self.mGrapher.menuAction())
        self.menubar.addAction(self.mEdit.menuAction())
        self.menubar.addAction(self.mPref.menuAction())
        self.menubar.addAction(self.mHelp.menuAction())

        self.retranslateUi(mwGrapher)
        self.tabGraph.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(mwGrapher)

    def retranslateUi(self, mwGrapher):
        mwGrapher.setWindowTitle(_translate("mwGrapher", "Grapher", None))
        self.mPref.setTitle(_translate("mwGrapher", "Pref", None))
        self.mToolsBar.setTitle(_translate("mwGrapher", "Tools Bar", None))
        self.mBarOrientation.setTitle(_translate("mwGrapher", "Bar Orientation", None))
        self.mTabOrientation.setTitle(_translate("mwGrapher", "Tab Orientation", None))
        self.mStyle.setTitle(_translate("mwGrapher", "Style", None))
        self.mHelp.setTitle(_translate("mwGrapher", "Help", None))
        self.mEdit.setTitle(_translate("mwGrapher", "Edit", None))
        self.mGrapher.setTitle(_translate("mwGrapher", "Grapher", None))
        self.tbTools.setWindowTitle(_translate("mwGrapher", "toolBar", None))
        self.miNorth2.setText(_translate("mwGrapher", "North", None))
        self.miSouth2.setText(_translate("mwGrapher", "South", None))
        self.miWest2.setText(_translate("mwGrapher", "West", None))
        self.miEast2.setText(_translate("mwGrapher", "East", None))
        self.miConnectNodes.setText(_translate("mwGrapher", "Connect Nodes", None))
        self.miTabNorth.setText(_translate("mwGrapher", "North", None))
        self.miTabSouth.setText(_translate("mwGrapher", "South", None))
        self.miTabWest.setText(_translate("mwGrapher", "West", None))
        self.miTabEast.setText(_translate("mwGrapher", "East", None))
        self.miAddGraphZone.setText(_translate("mwGrapher", "Add GraphZone", None))
        self.miBarHorizontal.setText(_translate("mwGrapher", "Horizontal", None))
        self.miBarVertical.setText(_translate("mwGrapher", "Vertical", None))
        self.miDefaultStyle.setText(_translate("mwGrapher", "Default", None))
        self.miDarkOrange.setText(_translate("mwGrapher", "Dark Orange", None))
        self.miDarkGrey.setText(_translate("mwGrapher", "Dark Grey", None))
        self.miRedGrey.setText(_translate("mwGrapher", "Red Grey", None))
        self.miShowToolBar.setText(_translate("mwGrapher", "Show", None))
        self.miHideToolBar.setText(_translate("mwGrapher", "Hide", None))
        self.miToolBarVisibility.setText(_translate("mwGrapher", "ToolBar Visibility", None))
        self.miParamsVisibility.setText(_translate("mwGrapher", "Params Visibility", None))

