# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\tools\maya\cloth\vtxMap\ui\wgVtxFile.ui'
#
# Created: Sun Mar 22 03:01:27 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_wgVtxFile(object):
    def setupUi(self, wgVtxFile):
        wgVtxFile.setObjectName(_fromUtf8("wgVtxFile"))
        wgVtxFile.resize(451, 283)
        self.gridLayout_4 = QtGui.QGridLayout(wgVtxFile)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(wgVtxFile)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tiBank = QtGui.QWidget()
        self.tiBank.setObjectName(_fromUtf8("tiBank"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tiBank)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.treeWidget = QtGui.QTreeWidget(self.tiBank)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_5.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tiBank, _fromUtf8(""))
        self.tiUser = QtGui.QWidget()
        self.tiUser.setObjectName(_fromUtf8("tiUser"))
        self.gridLayout = QtGui.QGridLayout(self.tiUser)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabFile = QtGui.QTabWidget(self.tiUser)
        self.tabFile.setObjectName(_fromUtf8("tabFile"))
        self.tiLoad = QtGui.QWidget()
        self.tiLoad.setObjectName(_fromUtf8("tiLoad"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tiLoad)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pbLoad = QtGui.QPushButton(self.tiLoad)
        self.pbLoad.setObjectName(_fromUtf8("pbLoad"))
        self.gridLayout_3.addWidget(self.pbLoad, 6, 0, 1, 1)
        self.lImportTitle = QtGui.QLabel(self.tiLoad)
        self.lImportTitle.setMinimumSize(QtCore.QSize(0, 14))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lImportTitle.setFont(font)
        self.lImportTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lImportTitle.setObjectName(_fromUtf8("lImportTitle"))
        self.gridLayout_3.addWidget(self.lImportTitle, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.tiLoad)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_3.addWidget(self.line_4, 1, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.tiLoad)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_3.addWidget(self.line_6, 5, 0, 1, 1)
        self.hlImpRootPath = QtGui.QHBoxLayout()
        self.hlImpRootPath.setSpacing(2)
        self.hlImpRootPath.setObjectName(_fromUtf8("hlImpRootPath"))
        self.lImpRootPath = QtGui.QLabel(self.tiLoad)
        self.lImpRootPath.setMinimumSize(QtCore.QSize(60, 0))
        self.lImpRootPath.setMaximumSize(QtCore.QSize(60, 20))
        self.lImpRootPath.setObjectName(_fromUtf8("lImpRootPath"))
        self.hlImpRootPath.addWidget(self.lImpRootPath)
        self.leImpRootPath = QtGui.QLineEdit(self.tiLoad)
        self.leImpRootPath.setReadOnly(False)
        self.leImpRootPath.setObjectName(_fromUtf8("leImpRootPath"))
        self.hlImpRootPath.addWidget(self.leImpRootPath)
        self.pbSetImpPath = QtGui.QPushButton(self.tiLoad)
        self.pbSetImpPath.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbSetImpPath.setObjectName(_fromUtf8("pbSetImpPath"))
        self.hlImpRootPath.addWidget(self.pbSetImpPath)
        self.gridLayout_3.addLayout(self.hlImpRootPath, 2, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.tiLoad)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_3.addWidget(self.line_5, 3, 0, 1, 1)
        self.hlExpMode_2 = QtGui.QHBoxLayout()
        self.hlExpMode_2.setSpacing(12)
        self.hlExpMode_2.setObjectName(_fromUtf8("hlExpMode_2"))
        self.lLoadMode = QtGui.QLabel(self.tiLoad)
        self.lLoadMode.setMinimumSize(QtCore.QSize(60, 0))
        self.lLoadMode.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lLoadMode.setObjectName(_fromUtf8("lLoadMode"))
        self.hlExpMode_2.addWidget(self.lLoadMode)
        self.cbImpAll = QtGui.QCheckBox(self.tiLoad)
        self.cbImpAll.setChecked(True)
        self.cbImpAll.setObjectName(_fromUtf8("cbImpAll"))
        self.bgLoadMode = QtGui.QButtonGroup(wgVtxFile)
        self.bgLoadMode.setObjectName(_fromUtf8("bgLoadMode"))
        self.bgLoadMode.addButton(self.cbImpAll)
        self.hlExpMode_2.addWidget(self.cbImpAll)
        self.cbImpSel = QtGui.QCheckBox(self.tiLoad)
        self.cbImpSel.setObjectName(_fromUtf8("cbImpSel"))
        self.bgLoadMode.addButton(self.cbImpSel)
        self.hlExpMode_2.addWidget(self.cbImpSel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlExpMode_2.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.hlExpMode_2, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 7, 0, 1, 1)
        self.tabFile.addTab(self.tiLoad, _fromUtf8(""))
        self.tiSave = QtGui.QWidget()
        self.tiSave.setObjectName(_fromUtf8("tiSave"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tiSave)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.hlExpRootPath = QtGui.QHBoxLayout()
        self.hlExpRootPath.setSpacing(2)
        self.hlExpRootPath.setObjectName(_fromUtf8("hlExpRootPath"))
        self.lExpRootPath = QtGui.QLabel(self.tiSave)
        self.lExpRootPath.setMinimumSize(QtCore.QSize(60, 0))
        self.lExpRootPath.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lExpRootPath.setObjectName(_fromUtf8("lExpRootPath"))
        self.hlExpRootPath.addWidget(self.lExpRootPath)
        self.leExpRootPath = QtGui.QLineEdit(self.tiSave)
        self.leExpRootPath.setReadOnly(False)
        self.leExpRootPath.setObjectName(_fromUtf8("leExpRootPath"))
        self.hlExpRootPath.addWidget(self.leExpRootPath)
        self.pbSetExpPath = QtGui.QPushButton(self.tiSave)
        self.pbSetExpPath.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbSetExpPath.setObjectName(_fromUtf8("pbSetExpPath"))
        self.hlExpRootPath.addWidget(self.pbSetExpPath)
        self.gridLayout_2.addLayout(self.hlExpRootPath, 2, 0, 1, 1)
        self.lExportTitle = QtGui.QLabel(self.tiSave)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lExportTitle.setFont(font)
        self.lExportTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lExportTitle.setObjectName(_fromUtf8("lExportTitle"))
        self.gridLayout_2.addWidget(self.lExportTitle, 0, 0, 1, 1)
        self.pbSave = QtGui.QPushButton(self.tiSave)
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.gridLayout_2.addWidget(self.pbSave, 6, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.tiSave)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 5, 0, 1, 1)
        self.line = QtGui.QFrame(self.tiSave)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tiSave)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 1)
        self.hlExpMode = QtGui.QHBoxLayout()
        self.hlExpMode.setSpacing(12)
        self.hlExpMode.setObjectName(_fromUtf8("hlExpMode"))
        self.lSaveMode = QtGui.QLabel(self.tiSave)
        self.lSaveMode.setMinimumSize(QtCore.QSize(60, 0))
        self.lSaveMode.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lSaveMode.setObjectName(_fromUtf8("lSaveMode"))
        self.hlExpMode.addWidget(self.lSaveMode)
        self.cbExpAll = QtGui.QCheckBox(self.tiSave)
        self.cbExpAll.setChecked(True)
        self.cbExpAll.setObjectName(_fromUtf8("cbExpAll"))
        self.bgSaveMode = QtGui.QButtonGroup(wgVtxFile)
        self.bgSaveMode.setObjectName(_fromUtf8("bgSaveMode"))
        self.bgSaveMode.addButton(self.cbExpAll)
        self.hlExpMode.addWidget(self.cbExpAll)
        self.cbExpSel = QtGui.QCheckBox(self.tiSave)
        self.cbExpSel.setObjectName(_fromUtf8("cbExpSel"))
        self.bgSaveMode.addButton(self.cbExpSel)
        self.hlExpMode.addWidget(self.cbExpSel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlExpMode.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.hlExpMode, 4, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 7, 0, 1, 1)
        self.tabFile.addTab(self.tiSave, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabFile, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tiUser, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(wgVtxFile)
        self.tabWidget.setCurrentIndex(0)
        self.tabFile.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wgVtxFile)

    def retranslateUi(self, wgVtxFile):
        wgVtxFile.setWindowTitle(_translate("wgVtxFile", "VtxFile", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tiBank), _translate("wgVtxFile", "Bank", None))
        self.pbLoad.setText(_translate("wgVtxFile", "Load", None))
        self.lImportTitle.setText(_translate("wgVtxFile", "Import Vertex Map", None))
        self.lImpRootPath.setText(_translate("wgVtxFile", "Root Path:", None))
        self.pbSetImpPath.setText(_translate("wgVtxFile", "Set", None))
        self.lLoadMode.setText(_translate("wgVtxFile", "Load Mode: ", None))
        self.cbImpAll.setText(_translate("wgVtxFile", "All Vtx Maps", None))
        self.cbImpSel.setText(_translate("wgVtxFile", "Selected Vtx Map", None))
        self.tabFile.setTabText(self.tabFile.indexOf(self.tiLoad), _translate("wgVtxFile", "Load", None))
        self.lExpRootPath.setText(_translate("wgVtxFile", "Root Path:", None))
        self.pbSetExpPath.setText(_translate("wgVtxFile", "Set", None))
        self.lExportTitle.setText(_translate("wgVtxFile", "Export Vertex Map", None))
        self.pbSave.setText(_translate("wgVtxFile", "Save", None))
        self.lSaveMode.setText(_translate("wgVtxFile", "Save Mode: ", None))
        self.cbExpAll.setText(_translate("wgVtxFile", "All Vtx Maps", None))
        self.cbExpSel.setText(_translate("wgVtxFile", "Selected Vtx Map", None))
        self.tabFile.setTabText(self.tabFile.indexOf(self.tiSave), _translate("wgVtxFile", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tiUser), _translate("wgVtxFile", "User", None))

