# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio\tools\maya\cloth\clothBox\ud\wgRiggBox.ui'
#
# Created: Sat Jun 06 18:07:38 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_wgRiggBox(object):
    def setupUi(self, wgRiggBox):
        wgRiggBox.setObjectName(_fromUtf8("wgRiggBox"))
        wgRiggBox.resize(299, 348)
        self.gridLayout = QtGui.QGridLayout(wgRiggBox)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.qfRigid = QtGui.QFrame(wgRiggBox)
        self.qfRigid.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfRigid.setObjectName(_fromUtf8("qfRigid"))
        self.vlCloth_2 = QtGui.QVBoxLayout(self.qfRigid)
        self.vlCloth_2.setSpacing(0)
        self.vlCloth_2.setContentsMargins(2, 0, 2, 0)
        self.vlCloth_2.setObjectName(_fromUtf8("vlCloth_2"))
        self.hlRigidDriver = QtGui.QHBoxLayout()
        self.hlRigidDriver.setSpacing(2)
        self.hlRigidDriver.setObjectName(_fromUtf8("hlRigidDriver"))
        self.lRigidDriver = QtGui.QLabel(self.qfRigid)
        self.lRigidDriver.setMinimumSize(QtCore.QSize(80, 0))
        self.lRigidDriver.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lRigidDriver.setAlignment(QtCore.Qt.AlignCenter)
        self.lRigidDriver.setObjectName(_fromUtf8("lRigidDriver"))
        self.hlRigidDriver.addWidget(self.lRigidDriver)
        self.leRigidDriver = QtGui.QLineEdit(self.qfRigid)
        self.leRigidDriver.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leRigidDriver.setFrame(True)
        self.leRigidDriver.setReadOnly(True)
        self.leRigidDriver.setObjectName(_fromUtf8("leRigidDriver"))
        self.hlRigidDriver.addWidget(self.leRigidDriver)
        self.pbPickRigidDriver = QtGui.QPushButton(self.qfRigid)
        self.pbPickRigidDriver.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbPickRigidDriver.setObjectName(_fromUtf8("pbPickRigidDriver"))
        self.hlRigidDriver.addWidget(self.pbPickRigidDriver)
        self.vlCloth_2.addLayout(self.hlRigidDriver)
        self.hlRigidSolver = QtGui.QHBoxLayout()
        self.hlRigidSolver.setSpacing(2)
        self.hlRigidSolver.setObjectName(_fromUtf8("hlRigidSolver"))
        self.lRigidSolver = QtGui.QLabel(self.qfRigid)
        self.lRigidSolver.setMinimumSize(QtCore.QSize(80, 0))
        self.lRigidSolver.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lRigidSolver.setAlignment(QtCore.Qt.AlignCenter)
        self.lRigidSolver.setObjectName(_fromUtf8("lRigidSolver"))
        self.hlRigidSolver.addWidget(self.lRigidSolver)
        self.cbRigidSolver = QtGui.QComboBox(self.qfRigid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbRigidSolver.sizePolicy().hasHeightForWidth())
        self.cbRigidSolver.setSizePolicy(sizePolicy)
        self.cbRigidSolver.setObjectName(_fromUtf8("cbRigidSolver"))
        self.cbRigidSolver.addItem(_fromUtf8(""))
        self.hlRigidSolver.addWidget(self.cbRigidSolver)
        self.pbRigidSolverRf = QtGui.QPushButton(self.qfRigid)
        self.pbRigidSolverRf.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbRigidSolverRf.setObjectName(_fromUtf8("pbRigidSolverRf"))
        self.hlRigidSolver.addWidget(self.pbRigidSolverRf)
        self.vlCloth_2.addLayout(self.hlRigidSolver)
        self.hlRigidMesh = QtGui.QHBoxLayout()
        self.hlRigidMesh.setSpacing(2)
        self.hlRigidMesh.setObjectName(_fromUtf8("hlRigidMesh"))
        self.lRigidMesh = QtGui.QLabel(self.qfRigid)
        self.lRigidMesh.setMinimumSize(QtCore.QSize(80, 0))
        self.lRigidMesh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lRigidMesh.setAlignment(QtCore.Qt.AlignCenter)
        self.lRigidMesh.setObjectName(_fromUtf8("lRigidMesh"))
        self.hlRigidMesh.addWidget(self.lRigidMesh)
        self.leRigidMesh = QtGui.QLineEdit(self.qfRigid)
        self.leRigidMesh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leRigidMesh.setFrame(True)
        self.leRigidMesh.setReadOnly(True)
        self.leRigidMesh.setObjectName(_fromUtf8("leRigidMesh"))
        self.hlRigidMesh.addWidget(self.leRigidMesh)
        self.pbPickRigidMesh = QtGui.QPushButton(self.qfRigid)
        self.pbPickRigidMesh.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbPickRigidMesh.setObjectName(_fromUtf8("pbPickRigidMesh"))
        self.hlRigidMesh.addWidget(self.pbPickRigidMesh)
        self.vlCloth_2.addLayout(self.hlRigidMesh)
        self.hlRigidResult = QtGui.QHBoxLayout()
        self.hlRigidResult.setSpacing(2)
        self.hlRigidResult.setObjectName(_fromUtf8("hlRigidResult"))
        self.lRigidResult = QtGui.QLabel(self.qfRigid)
        self.lRigidResult.setMinimumSize(QtCore.QSize(80, 0))
        self.lRigidResult.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lRigidResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lRigidResult.setObjectName(_fromUtf8("lRigidResult"))
        self.hlRigidResult.addWidget(self.lRigidResult)
        self.leRigidResult = QtGui.QLineEdit(self.qfRigid)
        self.leRigidResult.setEnabled(False)
        self.leRigidResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leRigidResult.setObjectName(_fromUtf8("leRigidResult"))
        self.hlRigidResult.addWidget(self.leRigidResult)
        self.vlCloth_2.addLayout(self.hlRigidResult)
        self.hlRigidMode = QtGui.QHBoxLayout()
        self.hlRigidMode.setSpacing(2)
        self.hlRigidMode.setObjectName(_fromUtf8("hlRigidMode"))
        self.lRigidMode = QtGui.QLabel(self.qfRigid)
        self.lRigidMode.setMinimumSize(QtCore.QSize(80, 0))
        self.lRigidMode.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lRigidMode.setAlignment(QtCore.Qt.AlignCenter)
        self.lRigidMode.setObjectName(_fromUtf8("lRigidMode"))
        self.hlRigidMode.addWidget(self.lRigidMode)
        self.rbCollide = QtGui.QRadioButton(self.qfRigid)
        self.rbCollide.setChecked(True)
        self.rbCollide.setObjectName(_fromUtf8("rbCollide"))
        self.bgRigidMode = QtGui.QButtonGroup(wgRiggBox)
        self.bgRigidMode.setObjectName(_fromUtf8("bgRigidMode"))
        self.bgRigidMode.addButton(self.rbCollide)
        self.hlRigidMode.addWidget(self.rbCollide)
        self.rbPushOut = QtGui.QRadioButton(self.qfRigid)
        self.rbPushOut.setObjectName(_fromUtf8("rbPushOut"))
        self.bgRigidMode.addButton(self.rbPushOut)
        self.hlRigidMode.addWidget(self.rbPushOut)
        self.rbPassive = QtGui.QRadioButton(self.qfRigid)
        self.rbPassive.setObjectName(_fromUtf8("rbPassive"))
        self.bgRigidMode.addButton(self.rbPassive)
        self.hlRigidMode.addWidget(self.rbPassive)
        self.vlCloth_2.addLayout(self.hlRigidMode)
        self.hlCreateRigid = QtGui.QHBoxLayout()
        self.hlCreateRigid.setSpacing(2)
        self.hlCreateRigid.setContentsMargins(-1, 0, -1, -1)
        self.hlCreateRigid.setObjectName(_fromUtf8("hlCreateRigid"))
        self.pbCreateRigid = QtGui.QPushButton(self.qfRigid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCreateRigid.sizePolicy().hasHeightForWidth())
        self.pbCreateRigid.setSizePolicy(sizePolicy)
        self.pbCreateRigid.setIconSize(QtCore.QSize(24, 24))
        self.pbCreateRigid.setFlat(True)
        self.pbCreateRigid.setObjectName(_fromUtf8("pbCreateRigid"))
        self.hlCreateRigid.addWidget(self.pbCreateRigid)
        self.cbSmoothMesh = QtGui.QCheckBox(self.qfRigid)
        self.cbSmoothMesh.setObjectName(_fromUtf8("cbSmoothMesh"))
        self.hlCreateRigid.addWidget(self.cbSmoothMesh)
        self.vlCloth_2.addLayout(self.hlCreateRigid)
        self.gridLayout.addWidget(self.qfRigid, 4, 0, 1, 1)
        self.qfConstraint = QtGui.QFrame(wgRiggBox)
        self.qfConstraint.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfConstraint.setObjectName(_fromUtf8("qfConstraint"))
        self.verticalLayout = QtGui.QVBoxLayout(self.qfConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hlConstraint = QtGui.QHBoxLayout()
        self.hlConstraint.setSpacing(2)
        self.hlConstraint.setObjectName(_fromUtf8("hlConstraint"))
        self.lConstraint = QtGui.QLabel(self.qfConstraint)
        self.lConstraint.setMinimumSize(QtCore.QSize(80, 0))
        self.lConstraint.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lConstraint.setAlignment(QtCore.Qt.AlignCenter)
        self.lConstraint.setObjectName(_fromUtf8("lConstraint"))
        self.hlConstraint.addWidget(self.lConstraint)
        self.leConstraint = QtGui.QLineEdit(self.qfConstraint)
        self.leConstraint.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leConstraint.setFrame(True)
        self.leConstraint.setReadOnly(True)
        self.leConstraint.setObjectName(_fromUtf8("leConstraint"))
        self.hlConstraint.addWidget(self.leConstraint)
        self.pbPickConstraint = QtGui.QPushButton(self.qfConstraint)
        self.pbPickConstraint.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbPickConstraint.setObjectName(_fromUtf8("pbPickConstraint"))
        self.hlConstraint.addWidget(self.pbPickConstraint)
        self.verticalLayout.addLayout(self.hlConstraint)
        self.hlConstResult = QtGui.QHBoxLayout()
        self.hlConstResult.setSpacing(2)
        self.hlConstResult.setObjectName(_fromUtf8("hlConstResult"))
        self.lConstResult = QtGui.QLabel(self.qfConstraint)
        self.lConstResult.setMinimumSize(QtCore.QSize(80, 0))
        self.lConstResult.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lConstResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lConstResult.setObjectName(_fromUtf8("lConstResult"))
        self.hlConstResult.addWidget(self.lConstResult)
        self.leConstResult = QtGui.QLineEdit(self.qfConstraint)
        self.leConstResult.setEnabled(False)
        self.leConstResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leConstResult.setObjectName(_fromUtf8("leConstResult"))
        self.hlConstResult.addWidget(self.leConstResult)
        self.verticalLayout.addLayout(self.hlConstResult)
        self.pbStoreConst = QtGui.QPushButton(self.qfConstraint)
        self.pbStoreConst.setIconSize(QtCore.QSize(24, 24))
        self.pbStoreConst.setFlat(True)
        self.pbStoreConst.setObjectName(_fromUtf8("pbStoreConst"))
        self.verticalLayout.addWidget(self.pbStoreConst)
        self.gridLayout.addWidget(self.qfConstraint, 5, 0, 1, 1)
        self.qfCloth = QtGui.QFrame(wgRiggBox)
        self.qfCloth.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfCloth.setObjectName(_fromUtf8("qfCloth"))
        self.vlCloth = QtGui.QVBoxLayout(self.qfCloth)
        self.vlCloth.setSpacing(0)
        self.vlCloth.setContentsMargins(2, 0, 2, 0)
        self.vlCloth.setObjectName(_fromUtf8("vlCloth"))
        self.hlClothDriver = QtGui.QHBoxLayout()
        self.hlClothDriver.setSpacing(2)
        self.hlClothDriver.setObjectName(_fromUtf8("hlClothDriver"))
        self.lClothDriver = QtGui.QLabel(self.qfCloth)
        self.lClothDriver.setMinimumSize(QtCore.QSize(80, 0))
        self.lClothDriver.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lClothDriver.setAlignment(QtCore.Qt.AlignCenter)
        self.lClothDriver.setObjectName(_fromUtf8("lClothDriver"))
        self.hlClothDriver.addWidget(self.lClothDriver)
        self.leClothDriver = QtGui.QLineEdit(self.qfCloth)
        self.leClothDriver.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leClothDriver.setFrame(True)
        self.leClothDriver.setReadOnly(True)
        self.leClothDriver.setObjectName(_fromUtf8("leClothDriver"))
        self.hlClothDriver.addWidget(self.leClothDriver)
        self.pbPickClothDriver = QtGui.QPushButton(self.qfCloth)
        self.pbPickClothDriver.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbPickClothDriver.setObjectName(_fromUtf8("pbPickClothDriver"))
        self.hlClothDriver.addWidget(self.pbPickClothDriver)
        self.vlCloth.addLayout(self.hlClothDriver)
        self.hlClothSolver = QtGui.QHBoxLayout()
        self.hlClothSolver.setSpacing(2)
        self.hlClothSolver.setObjectName(_fromUtf8("hlClothSolver"))
        self.lClothSolver = QtGui.QLabel(self.qfCloth)
        self.lClothSolver.setMinimumSize(QtCore.QSize(80, 0))
        self.lClothSolver.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lClothSolver.setAlignment(QtCore.Qt.AlignCenter)
        self.lClothSolver.setObjectName(_fromUtf8("lClothSolver"))
        self.hlClothSolver.addWidget(self.lClothSolver)
        self.cbClothSolver = QtGui.QComboBox(self.qfCloth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbClothSolver.sizePolicy().hasHeightForWidth())
        self.cbClothSolver.setSizePolicy(sizePolicy)
        self.cbClothSolver.setObjectName(_fromUtf8("cbClothSolver"))
        self.cbClothSolver.addItem(_fromUtf8(""))
        self.hlClothSolver.addWidget(self.cbClothSolver)
        self.pbClothSolverRf = QtGui.QPushButton(self.qfCloth)
        self.pbClothSolverRf.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbClothSolverRf.setObjectName(_fromUtf8("pbClothSolverRf"))
        self.hlClothSolver.addWidget(self.pbClothSolverRf)
        self.vlCloth.addLayout(self.hlClothSolver)
        self.hlClothMesh = QtGui.QHBoxLayout()
        self.hlClothMesh.setSpacing(2)
        self.hlClothMesh.setObjectName(_fromUtf8("hlClothMesh"))
        self.lClothMesh = QtGui.QLabel(self.qfCloth)
        self.lClothMesh.setMinimumSize(QtCore.QSize(80, 0))
        self.lClothMesh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lClothMesh.setAlignment(QtCore.Qt.AlignCenter)
        self.lClothMesh.setObjectName(_fromUtf8("lClothMesh"))
        self.hlClothMesh.addWidget(self.lClothMesh)
        self.leClothMesh = QtGui.QLineEdit(self.qfCloth)
        self.leClothMesh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leClothMesh.setFrame(True)
        self.leClothMesh.setReadOnly(True)
        self.leClothMesh.setObjectName(_fromUtf8("leClothMesh"))
        self.hlClothMesh.addWidget(self.leClothMesh)
        self.pbPickClothMesh = QtGui.QPushButton(self.qfCloth)
        self.pbPickClothMesh.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pbPickClothMesh.setObjectName(_fromUtf8("pbPickClothMesh"))
        self.hlClothMesh.addWidget(self.pbPickClothMesh)
        self.vlCloth.addLayout(self.hlClothMesh)
        self.hlClothResult = QtGui.QHBoxLayout()
        self.hlClothResult.setSpacing(2)
        self.hlClothResult.setObjectName(_fromUtf8("hlClothResult"))
        self.lClothResult = QtGui.QLabel(self.qfCloth)
        self.lClothResult.setMinimumSize(QtCore.QSize(80, 0))
        self.lClothResult.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lClothResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lClothResult.setObjectName(_fromUtf8("lClothResult"))
        self.hlClothResult.addWidget(self.lClothResult)
        self.leClothResult = QtGui.QLineEdit(self.qfCloth)
        self.leClothResult.setEnabled(False)
        self.leClothResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leClothResult.setObjectName(_fromUtf8("leClothResult"))
        self.hlClothResult.addWidget(self.leClothResult)
        self.vlCloth.addLayout(self.hlClothResult)
        self.hlCreateCloth = QtGui.QHBoxLayout()
        self.hlCreateCloth.setSpacing(2)
        self.hlCreateCloth.setContentsMargins(-1, 0, -1, -1)
        self.hlCreateCloth.setObjectName(_fromUtf8("hlCreateCloth"))
        self.pbCreateCloth = QtGui.QPushButton(self.qfCloth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCreateCloth.sizePolicy().hasHeightForWidth())
        self.pbCreateCloth.setSizePolicy(sizePolicy)
        self.pbCreateCloth.setIconSize(QtCore.QSize(24, 24))
        self.pbCreateCloth.setFlat(True)
        self.pbCreateCloth.setObjectName(_fromUtf8("pbCreateCloth"))
        self.hlCreateCloth.addWidget(self.pbCreateCloth)
        self.cbForceWrap = QtGui.QCheckBox(self.qfCloth)
        self.cbForceWrap.setObjectName(_fromUtf8("cbForceWrap"))
        self.hlCreateCloth.addWidget(self.cbForceWrap)
        self.vlCloth.addLayout(self.hlCreateCloth)
        self.gridLayout.addWidget(self.qfCloth, 3, 0, 1, 1)
        self.hlSolverMethod = QtGui.QHBoxLayout()
        self.hlSolverMethod.setSpacing(2)
        self.hlSolverMethod.setContentsMargins(2, 0, 2, -1)
        self.hlSolverMethod.setObjectName(_fromUtf8("hlSolverMethod"))
        self.lSolverMethod = QtGui.QLabel(wgRiggBox)
        self.lSolverMethod.setMinimumSize(QtCore.QSize(80, 0))
        self.lSolverMethod.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lSolverMethod.setAlignment(QtCore.Qt.AlignCenter)
        self.lSolverMethod.setObjectName(_fromUtf8("lSolverMethod"))
        self.hlSolverMethod.addWidget(self.lSolverMethod)
        self.cbSolverMethod = QtGui.QComboBox(wgRiggBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSolverMethod.sizePolicy().hasHeightForWidth())
        self.cbSolverMethod.setSizePolicy(sizePolicy)
        self.cbSolverMethod.setObjectName(_fromUtf8("cbSolverMethod"))
        self.cbSolverMethod.addItem(_fromUtf8(""))
        self.cbSolverMethod.addItem(_fromUtf8(""))
        self.hlSolverMethod.addWidget(self.cbSolverMethod)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlSolverMethod.addItem(spacerItem)
        self.gridLayout.addLayout(self.hlSolverMethod, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.line = QtGui.QFrame(wgRiggBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(wgRiggBox)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 0, 1, 1)

        self.retranslateUi(wgRiggBox)
        QtCore.QMetaObject.connectSlotsByName(wgRiggBox)

    def retranslateUi(self, wgRiggBox):
        wgRiggBox.setWindowTitle(_translate("wgRiggBox", "Rigg Box", None))
        self.lRigidDriver.setText(_translate("wgRiggBox", "Rigid Driver: ", None))
        self.pbPickRigidDriver.setText(_translate("wgRiggBox", "Pick", None))
        self.lRigidSolver.setText(_translate("wgRiggBox", "Solver: ", None))
        self.cbRigidSolver.setItemText(0, _translate("wgRiggBox", "New Nucleus", None))
        self.pbRigidSolverRf.setText(_translate("wgRiggBox", "Refresh", None))
        self.lRigidMesh.setText(_translate("wgRiggBox", "Rigid Mesh: ", None))
        self.pbPickRigidMesh.setText(_translate("wgRiggBox", "Pick", None))
        self.lRigidResult.setText(_translate("wgRiggBox", "Result: ", None))
        self.lRigidMode.setText(_translate("wgRiggBox", "Mode: ", None))
        self.rbCollide.setText(_translate("wgRiggBox", "Collide", None))
        self.rbPushOut.setText(_translate("wgRiggBox", "PushOut", None))
        self.rbPassive.setText(_translate("wgRiggBox", "Passive", None))
        self.pbCreateRigid.setText(_translate("wgRiggBox", "Create Rigid", None))
        self.cbSmoothMesh.setText(_translate("wgRiggBox", "Smooth Mesh", None))
        self.lConstraint.setText(_translate("wgRiggBox", "Dyn Constraint: ", None))
        self.pbPickConstraint.setText(_translate("wgRiggBox", "Pick", None))
        self.lConstResult.setText(_translate("wgRiggBox", "Result: ", None))
        self.pbStoreConst.setText(_translate("wgRiggBox", "Store Constraint", None))
        self.lClothDriver.setText(_translate("wgRiggBox", "Cloth Driver: ", None))
        self.pbPickClothDriver.setText(_translate("wgRiggBox", "Pick", None))
        self.lClothSolver.setText(_translate("wgRiggBox", "Solver: ", None))
        self.cbClothSolver.setItemText(0, _translate("wgRiggBox", "New Nucleus", None))
        self.pbClothSolverRf.setText(_translate("wgRiggBox", "Refresh", None))
        self.lClothMesh.setText(_translate("wgRiggBox", "Cloth Mesh: ", None))
        self.pbPickClothMesh.setText(_translate("wgRiggBox", "Pick", None))
        self.lClothResult.setText(_translate("wgRiggBox", "Result: ", None))
        self.pbCreateCloth.setText(_translate("wgRiggBox", "Create Cloth", None))
        self.cbForceWrap.setText(_translate("wgRiggBox", "Force Wrap", None))
        self.lSolverMethod.setText(_translate("wgRiggBox", "Solver Method: ", None))
        self.cbSolverMethod.setItemText(0, _translate("wgRiggBox", "One Nucleus For All", None))
        self.cbSolverMethod.setItemText(1, _translate("wgRiggBox", "One Nucleus By Mesh", None))

